---
title: CÁLCULO III  -- 2026-2
subtitle: Cálculo Diferencial de Várias Variáveis
number-sections: true
bibliography: ../biblio.bib
csl:  ../aims-mathematics.csl

nocite: |
  @thomas2, @diomara, @tromba,
  
format:
  html:
    toc: true
from: markdown+emoji
---
# Informações Básicas

- **Início e Fim do Período:** 03/08/2026 a 11/12/2026.

-  **Horário e sala:**\
[Quadro de Alocação de salas do IHS](http://159.112.185.66/home/index_simples) -- [acesso por celular](http://159.112.185.66/home_externo/index)  \

- **Material a ser utilizado**

  - [slides](https://reginaldodr.github.io/slides/calculo3/calculo3.pdf)
  
  - [Lista de Exercícios Stewart](../lista-stewart6aEd-calculo3.pdf)

  - [VAs Antigas](../provas/)
  
  
-  **Ementa:** EQUAÇÕES PARAMÉTRICAS. FUNÇÕES VETORIAIS. SUPERFÍCIES QUÁDRICAS E CILÍNDRICAS. FUNÇÕES DE VÁRIAS VARIÁVEIS, LIMITE, CONTINUIDADE, DERIVADAS DIRECIONAIS, OTIMIZAÇÃO E MULTIPLICADORES DE LAGRANGE.

# Turmas

## Turma M1 -- Engenharia {-}

- [Notas de aula](https://drive.google.com/drive/folders/1rEFOy8kWumnZN_iLKpwXhWohH_SAH4ziKSUSMHJIjwXaqjnP7jBqePD5s0RJ-vfRotwLquNN?usp=drive_link)

- [Cronograma](TurmaM1.qmd)

| Dia | Horário | Sala |
|----|----|----|
|Segunda |9h - 11h| Sala S01 IHS Prédio Alugado |
|Terça   |9h - 11h| Sala S01 IHS Prédio Alugado |
: {.striped .table-sm}

## Turma C1 -- Computação {-}

- [Notas de aula](https://drive.google.com/drive/folders/1HLWqyEelHgO-f-epX4cUPd5OvhEfocUmO25M-mcIsmnox0h2Z5g9lHRK7I7alheVI4S-1Fjn?usp=drive_link)

- [Cronograma](turmaC1.qmd)

| Dia | Horário | Sala |
|----|----|----|
|Segunda |11h - 13h| Sala S01 IHS Prédio Alugado |
|Terça   |11h - 13h| Sala S01 IHS Prédio Alugado |
: {.striped .table-sm}

---

# Apresentação do Curso

Este curso é constituído de dois módulos: **Funções Vetoriais e Superfícies** e **Funções de Várias Variáveis**.

O **livro texto** será referência [@stewart2], que **está disponíveis para empréstimo na Biblioteca do campus** -- [BRO](https://bibliotecas.uff.br/bro/). <span style="color:red"> É altamente recomendado que vocês consultem este material, de preferência o livro físico.</span>

As demais referência contidas na @sec-ref formam uma lista complementar/auxiliar do curso, foram usados principalmente na elaboração das notas de aulas e exemplos.

# Listas de Exercícios

Abaixo seguem os execícios da referência [@stewart2] que devem ser feitos. A distribuição está dada por seção. 

Veja a lista [aqui](../lista-stewart6aEd-calculo3.pdf)

O símbolo :pencil2: significa quais exercícios já podem ser feitos com o contéudo dado até o momento, enquanto o símbolo :lock: se refere àqueles que ainda não. A medida que o conteúdo em sala for avançando, novos exercícios serão desbloqueados.

- **Parametrização, coordenadas polares, superfícies e funções vetoriais**\

:lock: **§ 12.5 (Retas e Planos):** 3, 5, 7, 9, 23, 26, 31, 43, 45.\
:lock: **§ 12.6 (Cilindros e Quádricas):** 3, 5, 13, 15, 21-28, 29, 31, 33.\
:lock: **§ 10.3 (Coordenadas Polares):** 1, 3, 7, 9, 11, 15, 17, 19, 21, 23, 25, 29, 31, 33, 35, 37, 39, 41, 56.\
:lock: **§ 13.1 (Funções Vetoriais):** 7, 9, 11, 19-24, 27, 37, 38, 39.\
:lock: **§ 13.2 (Derivadas):** 3, 5, 17, 19, 21, 23, 25, 27 e 29.\
:lock: **§13.3 (Comprimento de arco e Curvatura):** 1, 3, 5, 11, 13, 15, 17(b), 19(b), 21, 23.\
:lock: **§ 13.4 (Velociade e Aceleração):** 3, 5, 11, 13, 19, 31,32, 41.\
---

- **Funções de Várias Variáveis**\

:lock: **§ 14.1 (Funções):** 11, 13, 15, 17, 19, 23, 25, 27, 30, 39, 41, 45, 49, 61, 63.\
:lock: **§ 14.2 (Limite e Continuidade):** 5, 7, 9, 11, 13, 15, 29, 31, 35, 39, 41.\
:lock: **§ 14.3 (Derivadas Parciais):** 15, 17, 21, 23, 25, 29, 31, 39, 41, 51, 53, 61, 63, 65.\
:lock: **§ 14.4 (Aproximação Linear):** 1, 3, 5, 11, 13, 21, 25, 27, 33, 35, 37.\
:lock: **§ 14.5 (Regra da Cadeia):** 1, 3, 5, 7, 15, 17, 19, 21, 23, 35, 43.\
:lock: **§ 14.6 (Vetor Gradiente):** 5, 7, 9, 11, 15, 17, 21, 23, 25, 29, 31, 34, 39, 41, 53.\
:lock: **§ 14.7 (Máximos e Mínimos):** 5, 7, 13, 15, 31, 33, 34, 35, 39, 41, 43, 47, 53.\
:lock: **§ 14.8 (Multiplicadores de Lagrange):** 3, 5, 9, 15, 17, 19, 41, 43.

Exercícios do **Stewart Vol. 2, 7ª Edição.**

:pencil2: § 14.7: 5, 7, 11, 13, 15, 31, 33, 34, 35, 39, 41, 43, 47, 53.\
:pencil2: § 14.8: 3, 5, 9, 15, 17, 19, ,21, 45.

# Referências {#sec-ref}


::: {#refs}
:::



# Avaliação

A avaliação será feita mediante **2 Verificações de Aprendizagem (VAs) Escritas**. A média parial (NP) será a média aritmética  entre elas, isto é, 
$$NP=\frac{VA_1+VA_2}{2}$$
De acordo com o Regulamento da UFF, a **Nota Final** é calculada da seguinte forma:

> 
Definida como sendo igual à média parcial, caso o discente tenha obtido aprovação direta, ou igual a 6(seis), se a aprovação foi obtida na verificação suplementar (VS). No caso de reprovação na VS, a nota final será o resultado do cálculo da média aritmética entre a média parcial e a nota obtida na VS.

## Objetivos {-}
As VAs tem como objetivos avaliar se o aluno:

- Aprendeu os conceitos e técnicas ensinados em sala de aula. 
- É capaz de interpretar as questões corretamente e formular soluções para os problemas propostos.
- É capaz de produzir soluções, em formato de texto, compreensíveis,  com nível de detalhamento e rigor adequados para que outros profissionais familiarizados com os conceitos possam entendê-las.
- Sabe determinar quando a solução proposta resolve de fato o problema. 
- Consegue desenvolver uma argumentação lógica-dedutiva para chegar-se à resposta final.


## Critério de correção das VAs {-}
Com base nos objetivos apresentados acima, os critério de correção serão: 

   1. Interpretação correta das questões.
   2. As soluções devem ser escrita com clareza, organização, rigor e detalhamento.
   3. Soluções desenvolvidas fora do conteúdo ensinado, mesmo que corretas, não serão consideradas.
   4. Questão com várias soluções será anulada.
   5. Resposta correta mas com solução errada será anulada. 

Além disso, durante às VAs, serão adotadas as seguinte medidas: 

- Proibido compartilhar material.
- Só é permitida a saída após entrega definitiva da VA, ou seja, não é permitido ir ao banheiro ou beber água sem entregar definitivamente a prova. A VA tem duração de no máximo 1h50.
- É permitida a **consulta a material** (livros, notas de aula, caderno, apostilas e etc.)  e uso de dispositivo computacional, como calculadora científica, ambos **sem acesso a internet**.
- Fraude detectada, mesmo depois, zera a nota.

## Segunda Chamada {-}

O Art. 98 do  [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) garante ao aluno  o direito a uma avaliação de **Segunda Chamada (VR)**, <span style="color:red">**sem a necessidade de justificativa!**</span> Portanto, aquele aluno que **não puder ou não quiser** fazer uma das VAs, poderá faltar que seu direito à Segunda Chamada será garantido.

O conteúdo da **Segunda Chamada** será <span style="color:red">**toda a matéria do semestre.**</span>

::: {.callout-warning}
## Importante

Como **não há a necessidade de justificar a falta nas avaliações** para ter o direito à Segunda Chamada garantido, alguns alunos usam este direito para fazer a Segunda Chamada quando não se sentem suficientemente preparados para alguma das avaliações. 

Por conta disso, o aluno que estiver em dúvida entre fazer a VA ou a Segunda chamada, poderá comparecer no dia da VA e tentar fazê-la. Caso não se sinta preparado, poderá desistir e ainda terá o direito a fazer a Segunda Chamada. Aqueles que permanecerem e entregarem definitivamente a VA não terão o direito à Segunda Chamada.
:::

## Verificação Suplementar {-}

Em concordância com o [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) em seu Art. 99, a **Verificação Suplementar (VS)** é vetada aos discentes já aprovados e é **obrigatória** para aqueles que tenham obtido média parcial entre 4.0 e 5.9, sendo esses dois limites incluídos.


