---
title: Consideraçẽos sobre didática e vínculos emocionais!
description: "Vínculos emocionais podem potencializar o aprendizado?"
author: "Reginaldo Demarque"
date: 16 04 2025
categories:
  - matemática
  - ensino
  - didática
draft: false
format:
  html:
    toc: false
---

# O que eu pensava sobre ensino

Quando eu cursei a disciplina [Didática](https://www3.dti.ufv.br/dti/catalogo/programa-analitico/62963) na faculdade de licenciatura em matemática, lembro-me de ter lido em algum livro da bibliografia algo do tipo  "A melhor didática é o domínio do conhecimento".

Na época isso fez muito sentido para mim. Hoje me pergunto, será mesmo que é a melhor didática? Obviamente é requisito  essencial para uma boa didática ou, como dizemos na matemática, uma **condição necessária**, mas meus 15 anos de magistério me dizem que **não é suficente**. 

Enquanto estudante de ensino médio pensava que a melhor maneira de ensinar matemática era uma boa explicação. E por uma boa explicação, eu entendia como aquela que explicasse os mínimos detalhes, os porquês e, sobretudo,  conseguisse anteceder todas as possíveis dúvidas que os alunos teriam. Uma ideia muito ingênua, porém não é de todo equivocada. 

Eu realmente acreditava que se um professor dominasse bem um conteúdo a ponto de saber responder qualquer coisa sobre aquele tema, ele seria capaz de ensiná-lo a qualquer aluno. **Como todo jovem, eu tinha a resposta para o problema do aprendizado de matemática!** O que faltava era apenas professores que dominassem a matemática suficientemente bem! Quanta ingenuidade!

O principal problema com esse pensamento é que eu estava olhando apenas para mim. Eu estava olhando para um espelho e me perguntando: Como **EU aprendo matemática**? Nunca percebi como os meus colegas ou meus irmãos viam e percebiam a matemática, ou a escola. Eu sempre gostei de matemática e, mais que isso, sempre gostei de estudar e de ir para a escola. Então, para mim o conteúdo bem ensinado em sala já era suficiente. Era deslumbrante! Mas qualquer um sabe que essa não é a regra na escola, na verdade é a excessão. 

O meu erro era pensar que o que valia para mim se estendia  para todos. E claramente isso não é verdade! 
Depois de cursar licenciatura em matématica e de passar a lecionar, eu acabei percebendo algo óbvio, cada um tem uma relação e uma experiência diferente com a matemática. E logo cheguei à seguinte conclusão 

> Só não aprende matemática quem acumula muitas lacunas de conhecimento básico. Isso leva a uma frustração lenta a cada nova etapa, quando se precisa da anterior e esta não está bem sedimentada. Essa frustração acumulada cria um bloqueio e uma aversão pelo tema. Que por sua vez, impedem o aprendizado. 

Novamente, um pensamento não de todo equivocado, mas que não é a única razão pela qual muitos não conseguem aprender um conteúdo. 

Claro que se um aluno não tem conhecimento básico, ele não vai aprender o mais avançado, vemos isso todos os dias em sala. Também é verdade que existe um momento certo para você ensinar certos conteúdos, isso aprendi com Vygostsky nas aula de licenciatura, chama-se [zona de desenvolvimento proximal](https://pt.wikipedia.org/wiki/Zona_de_desenvolvimento_proximal). Contudo, conhecimento básico sólido somente não é suficiente para se aprender matemática. Novamente, é uma condição necessária.



# Uma hipótese certamente não inovadora

Interesse em um tema é um ótmo catalizador da aprendizagem, mas também não é sufciente para que o aprendizado ocorra. Todos nós já vimos alunos muito interessados em um tema que, ao serem submetidos a professores totalmente desmotivados, acabam por perder o interesse ou não aprender nada. Aliás, muita gente acredita que essa é a chave, motivar o aluno!

Eu ainda acredito que são práticas essenciais para uma boa didática:

 - Domínio profundo do conhecimento a ser ensinado. 
 - Orientar e auxiliar os alunos a sedimentar seus conhecimentos básicos antes de partir para temas mais avançados, ou seja, tapar os buracos acumulados ao longo da formação.
 - Motivar e demonstrar para os alunos que o tema é importante para sua formação. 
 - Apresentar o tema de forma gradativa, do simples para o complexo. Adequando o conteúdo ao nível dos seus alunos. 
 
Acredito também que ninguém discorde desta lista. Porém, na sala de aula, vemos que essas práticas não são suficientes. 

Mesmo depois de cursar licenciatura em matemática, estudar Vygostsky, Piaget, Paulo Freire,  de lecionar por mais de 15 anos, eu nunca tinha parado para pensar em algo -- que talvez seja óbvio para muita gente -- mas que para mim começou a fazer sentido só agora. Algo que possa ser acrescentado a essa lista e que torne-a mais próxima das condições  suficientes para que os alunos aprendam tudo que eles estão prontos e dispostos a aprender. 

Minha hipótese é de que um elemento faltante é a **conexão emocional** que fazemos com nossos alunos. 

>A conexão emocional poder servir tanto para disparar a centelha da aprendizagem, daquele aluno que se sente incapaz de aprender o tema, como também pode ser o balde d'agua que apagará de vez o fogo do interesse, daquele aluno que é apaixonado pelo assunto.

A matemática é, indubitavelmente, uma ciência exata. Mas ensiná-la é uma atividade humana. Ensinar e aprender, são atividades humanas. E, pode parecer estranho o que vou dizer agora, mas humanos precisam se conectar emocionalmente para poder aprender! 

Certamente isso não é novo. Certamente já foi pensado e proposto por diversos pensadores do ensino em geral. Me vem imediatamente à mente as aulas de *psicologia da aprendizagem* da faculdade e as escolas com proposta de ensino socio-interacionista. 

O que eu entendo agora é que a minha conexão é diretamente com a matemática, com o conhecimento. Isso me basta. Mas muitas outras pessoas, acredito que a maioria, não tem essa conexão com a matemática. Digo isso, devido às incontáveis vezes que ouço a frase "odeio matemática", todas as vezes que digo minha profissão. Neste caso, essa conexão precisa ser criada de outra forma. 

Minha hipótese é que, como professores, precisamos criar conexões emocionais e verdadeiras com nossos estudantes para conseguirmos de fato alcançar o máximo de alunos.

Algumas evidências, tiradas apenas da minha percepção, que acredito corroboratem para essa hipótese são: 

 - Professores que tem a capacidade de ser engraçados ou cativantes, acabam tendo melhores resultados de aprendizado, independente da disciplina.
 - Professores que conseguem ser vistos como figura de grande respeito, também tem bons resultados.
 - Alunos que se identificam ou criam laços afetivos com os seus professores, acabam se dedicando com mais afinco, com a finalidade de não decepcioná-los. 
 - Professores de ensino infantil tem laços afetivos gigantes com seus alunos e também resultados fantásticos! Levamos algumas coisas que aprendemos nessa etapa por toda a vida.
 - Por outro lado, muitos professores do ensino superior que são extremamente profissionais e distantes, acabam por ter resultados de aprendizagem muito ruins, mesmo sendo altamente competente em suas áreas. 
 
Me entristece um pouco ter demorado tanto a perceber isso. Sinto que seja algo tão óbvio, mas que nunca me foi dito antes. Agora, além de testar essa hipótese em sala de aula, preciso buscar quais são os pensadores que se debruçaram sobre este tema. Assim que me aprofundar no tema, volto a escrever.


 




