project:
  type: website
  output-dir: docs
  

website:
  title: ""
  favicon: images/dchi-2.png
  site-url: https://demarque.mat.br
  description: "Professor Associado 3, RCN, UFF"
  twitter-card: true
  draft-mode: gone
  page-footer: 
    left: 
      - text: "LICENÇA CC-BY-NC-SA"
        href: licenca.qmd
    right:
      - text: Desenvolvido com Quarto
        href: https://quarto.org/
  navbar:
    logo: images/demarchi.png
    logo-href: index.qmd
    background: primary
    foreground: light
    pinned: true
    collapse: true
    left:
      - href: teaching.qmd
        text: Ensino
      - href: pesquisa.qmd
        text: Research
      - href: blog.qmd
        text: Blog
    right:
      - icon: youtube
        href: https://www.youtube.com/c/ProfReginaldoDemarque
        aria-label: YouTube
      - icon: github
        href: https://github.com/reginaldodr
        aria-label: GitHub
      - icon: mastodon
        aria-label: mastodon
        href: https://ursal.zone/@reginaldodr
      - text: "<img src='images/dchi-2.png' style='width: 20px; height: auto;' alt='Logo'>"
        href: logo.qmd


   
        

format:
  html:
    theme:
      light: journal
      dark: slate
    css: styles.css
    toc: false
    lang: pt
    date-format: DD/MM/YYYY
    link-external-icon: false
    link-external-newwindow: true



editor: source

