project:
  type: website
  output-dir: docs

website:
  title: "Prof. Reginaldo Demarque"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

