project:
  type: website
  output-dir: docs

website:
  title: "Prof. Reginaldo Demarque"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Ensino
      - href: pesquisa.qmd
        text: Research
      - href: blog.qmd
        text: blog
      - icon: youtube
        href: https://www.youtube.com/c/ProfReginaldoDemarque
        aria-label: YouTube  
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: pt
    date-format: DD/MM/YYYY

editor: source

