project:
  type: website
  output-dir: docs
  

website:
  title: "Prof. Reginaldo Demarque"
  twitter-card: true
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Ensino
      - href: pesquisa.qmd
        text: Research
      - href: blog.qmd
        text: Blog
      - icon: youtube
        href: https://www.youtube.com/c/ProfReginaldoDemarque
        aria-label: YouTube
      - icon: github
        href: https://github.com/reginaldodr
        aria-label: GitHub
      - icon: mastodon
        aria-label: mastodon
        href: https://ursal.zone/@reginaldodr
        

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    lang: pt
    date-format: DD/MM/YYYY
    link-external-icon: true
    link-external-newwindow: true


editor: source

