---
title: EQUAﾃ僌髭S DIFERENCIAIS PARCIAIS II -- 2026-1
number-sections: false

format:
  html:
    toc: true
from: markdown+emoji
---


¥begin{equation*}
¥begin{cases}
u_t+Lu=f, & ¥text{ em } ¥Omega ¥times (0,T)¥¥
u=0, & ¥text{ em } ¥partial¥Omega¥¥
u=g, & ¥text{ em } ¥Omega
¥end{cases}
¥end{equation*}

# Informaﾃｧﾃｵes Bﾃ｡sicas

- **Inﾃｭcio e Fim do Perﾃｭodo:** 09/03/26 a 10/07/26

-  **Horﾃ｡rio e sala:** ¥

| Dia | Horﾃ｡rio | Sala |Professor|
|--|----|:---:|----|
|Segunda |11h - 13h| Auditﾃｳrio da PGMAT|Luiz Viana|
|Quarta  |11h - 13h| Auditﾃｳrio da PGMAT|Reginaldo Demarque|
|Sexta   |11h - 13h| Auditﾃｳrio da PGMAT|Luiz Viana|
: {.striped .table-sm}

:::: {.columns}

- **Material a ser utilizado**

 - [Slides](https://reginaldodr.github.io/slides/EDPII/EDP2.pdf)¥

:::

# Cronograma Efetivado {#sec-crono}

A seguir temos a proposta de cronograma para este curso. Esta proposta pode sofrer pequenas alteraﾃｧﾃｵes ao longo do curso que,       caso ocorram, serﾃ｣o comunicadas aos alunos. **Cabe ressaltar que o semestre se encerra no dia  <span style="color:red"> 10/07 </span>,      neste caso, ﾃｩ aconselhado que fiquem disponﾃｭveis atﾃｩ esta data.**

<span style="color:standard"> **1. Distribuiﾃｧﾃｵes** </span>

01 . &nbsp; Seg  --  09/03  --  <span style="color:standard"> Apresentaﾃｧﾃ｣o do curso. Preliminares: Teorema de Fubini, espaﾃｧos $L^p$, Desigualdade de Hﾃｶlder. Partiﾃｧﾃ｣o da Unidade. Suporte de funﾃｧﾃｵes. </span> ¥
02 . &nbsp; Qua  --  11/03  --  <span style="color:standard"> Convoluﾃｧﾃ｣o. Desigualdade de Young.  </span> ¥
03 . &nbsp; Sex  --  13/03  --  <span style="color:standard"> Derivaﾃｧﾃ｣o de convoluﾃｧﾃ｣o. Funﾃｧﾃｵes regularizantes: definiﾃｧﾃ｣o e exemplo. </span> ¥
04 . &nbsp; Seg  --  16/03  --  <span style="color:standard"> Convergﾃｪncia das regularizaﾃｧﾃｵes. Densidade de $C_c^¥infty(¥Omega)$ em $L^p(¥Omega)$. Lema de Du Bois Raymond.  </span> ¥
05 . &nbsp; Qua  --  18/03  --  <span style="color:standard"> Espaﾃｧos das funﾃｧﾃｵes testes e distribiﾃｧﾃｵes. Convergﾃｪncia. Derivaﾃｧﾃ｣o de distribuiﾃｧﾃｵes. </span> ¥
06 . &nbsp; Sex  --  20/03  --  <span style="color:standard">  Derivada Fraca. Multiplicaﾃｧﾃ｣o de uma distribuiﾃｧﾃ｣o por funﾃｧﾃｵes $C^¥infty$.  </span> ¥
---

<span style="color:standard"> **2. Espaﾃｧos de Sobolev** </span>

07 . &nbsp; Seg  --  23/03  --  <span style="color:standard"> Definiﾃｧﾃ｣o de Espaﾃｧos de Sobolev  e exemplos.   </span> ¥
08 . &nbsp; Qua  --  25/03  --  <span style="color:standard"> Espaﾃｧos de Sobolev sﾃ｣o espaﾃｧos de Banach, reflexivos e separﾃ｡veis. </span> ¥
09 . &nbsp; Sex  --  27/03  --  <span style="color:standard"> $W^{k,p}(¥mathbb{R}^d)=W_0^{k,p}(¥mathbb{R}^d)$.   </span> ¥
10 . &nbsp; Seg  --  30/03  --  <span style="color:standard"> Aproximaﾃｧﾃ｣o por Funﾃｧﾃｵes Suaves. Teorema de Friedrichs.   </span> ¥
11 . &nbsp; Qua  --  01/04  --  <span style="color:standard"> Teorema de Meyers-Serrin.  </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  03/04  --  Sexta-feira da Paixﾃ｣o </span> ¥
12 . &nbsp; Seg  --  06/04  --  <span style="color:standard"> Regra da Cadeia. Contra-exemplo Meyers-Serrin $p=+¥infty$. Funﾃｧﾃｵes em $W^{k,p}(¥Omega)$ com suporte compacto estﾃ｣o em $W_0^{k,p}(¥Omega)$.  </span> ¥
13 . &nbsp; Qua  --  08/04  --  <span style="color:standard"> Teorema de Meyers-Serrin (finalizaﾃｧﾃ｣o). Definiﾃｧﾃ｣o de Operador Prolongamento. Definiﾃｧﾃ｣o de $¥partial¥Omega$ de classe $C^k$. Corolﾃ｡rio do Teorema do Prolongamento.  </span> ¥
14 . &nbsp; Sex  --  10/04  --  <span style="color:standard"> Lema do Teorema do Prolongamento: Caso $¥Omega=Q_1^+$ </span> ¥
15 . &nbsp; Seg  --  13/04  --  <span style="color:standard"> Lema do Teorema do Prolongamento finalizaﾃｧﾃ｣o. </span> ¥
16 . &nbsp; Qua  --  15/04  --  <span style="color:standard"> Operador Traﾃｧo: caso $¥Omega=¥mathbb{R}^N_+$. </span>¥
17 . &nbsp; Sex  --  17/04  --  <span style="color:standard"> Demonstraﾃｧﾃ｣o do Teorema do Prolongamento. </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  20/04  --  Ponto Facultativo  </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  21/04  --  Tiradentes </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  22/04  --  Ponto Facultativo </span> ¥
18 . &nbsp; Sex  --  24/04  --  <span style="color:standard"> Desigualdade de Gagliardo-Nirenberg-Sobolev </span> ¥
19 . &nbsp; Seg  --  27/04  --  <span style="color:standard"> Corolﾃ｡rio da Des. G-N-S. Imersﾃ｣o p=N. Definiﾃｧﾃ｣o de funﾃｧﾃｵes Hﾃｶlder contﾃｭnuas. </span> ¥
20 . &nbsp; Qua  --  29/04  --<span style="color:standard"> Teorema do Traﾃｧo. $¥ker(¥gamma_0)=W_0^{1,p}(¥Omega)$.   </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  01/05  --  Dia do Trabalho </span> ¥
21 . &nbsp; Seg  --  04/05  --  <span style="color:standard"> Desigualdade de Morrey. </span> ¥
22. &nbsp; Qua  --  06/05  --<span style="color:standard"> Integraﾃｧﾃ｣o por partes em $W^{1,p}(¥Omega)$. Enunciado do traﾃｧo geral para $H^k(¥Omega)$. Espaﾃｧos $H^{-1}(¥Omega)$  </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  08/05  --  Participaﾃｧﾃ｣o em Congresso </span> ¥
23 . &nbsp; Seg  --  11/05  --  <span style="color:standard"> Imersﾃｵes de Sobolev: Casos $¥Omega¥subset ¥mathbb{R}^N$. Desigualdade de Poincarﾃｩ. </span> ¥
24 . &nbsp; Qua  --  13/05  --  <span style="color:standard">Imersﾃｵes Compactas: Teorema de Rellich-Kondrachov. </span> ¥

<span style="color:red"> &nbsp; Qui  --  21/05  --  VA 1 (Verificaﾃｧﾃ｣o de Aprendizagem) </span> ¥
---

<span style="color:standard"> **3. Problemas Elﾃｭpticos e Parabﾃｳlicos ** </span>

25 . &nbsp; Sex  --  15/05  --  <span style="color:standard"> Introduﾃｧﾃ｣o ao problema elﾃｭptico. Definiﾃｧﾃ｣o de Soluﾃｧﾃ｣o fraca. Teorema de Lax-Milgran.</span> ¥
26 . &nbsp; Seg  --  18/05  --  <span style="color:standard"> Estimativas de energia. 1ﾂｺ Teorema de existﾃｪncia de soluﾃｧﾃ｣o fraca. Operador adjunto. </span> ¥
27 . &nbsp; Qua  --  20/05  --  <span style="color:standard"> Alternativa de Fredholm e 2ﾂｺ Teorema de Existﾃｪncia.  </span> ¥
29 . &nbsp; Sex  --  22/05  --  <span style="color:standard"> 3ﾂｺ Teorema de Existﾃｪncia: Problemas de autovalores </span> ¥
30 . &nbsp; Seg  --  25/05  --  <span style="color:standard"> Limitaﾃｧﾃ｣o da Inversa; regularidade do problema elﾃｭptico. </span> ¥
31 . &nbsp; Qua  --  27/05  --  <span style="color:standard"> Distribuiﾃｧﾃｵes Vetoriais </span> ¥
32 . &nbsp; Sex  --  29/05  --  <span style="color:standard"> Princﾃｭpio do mﾃ｡ximo fraco. </span> ¥
33 . &nbsp; Seg  --  01/06  --  <span style="color:standard"> Princﾃｭpio do mﾃ｡ximo fraco com c=0 (continuaﾃｧﾃ｣o); Demonstraﾃｧﾃ｣o o princﾃｭpio do mﾃ｡ximo fraco para c>=0 </span> ¥
34 . &nbsp; Qua  --  03/06  --  <span style="color:standard"> O problema Parabﾃｳlico. Definiﾃｧﾃ｣o de Soluﾃｧﾃ｣o Fraca. Base hilbertiana de autofunﾃｧﾃｵes do laplaciano. </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  04/06  --  Corpus Christ </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  05/06  --  Ponto Facultativo </span> ¥
35 . &nbsp; Seg  --  08/06  --  <span style="color:standard">Lema de Hopf</span> ¥
36 . &nbsp; Qua  --  10/06  --  <span style="color:standard"> Enunciado do Teorema de Existﾃｪncia. Desigualdade de Energia para uma soluﾃｧﾃ｣o fraca, dependﾃｪncia continua dos dados e prova da unicidade. Aproximaﾃｧﾃｵes de Galerkin.   </span> ¥
37 . &nbsp; Sex  --  12/06  --  <span style="color:standard"> Princﾃｭpio do Mﾃ｡ximo Forte. </span> ¥
38 . &nbsp; Seg  --  15/06  --  <span style="color:standard"> Revisﾃ｣o sobre a teoria espectral. Inﾃｭcio do estudo dos autovalores e das autofunﾃｧﾃｵes. </span> ¥
39 . &nbsp; Qua  --  17/06  --  <span style="color:standard"> Prova da existﾃｪncia de soluﾃｧﾃ｣o do problema parabﾃｳlico via mﾃｩtodo de Galerkin. </span> ¥
40 . &nbsp; Sex  --  19/06  --  <span style="color:standard">  </span> ¥
41 . &nbsp; Seg  --  22/06  --  <span style="color:standard">Princﾃｭpios do Mﾃ｡ximo Fraco parabﾃｳlico. </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  24/06  --  Feriado Municipal </span> ¥
42 . &nbsp; Sex  --  26/06  --  <span style="color:LightGray">Princﾃｭpio do Mﾃ｡ximo Fraco e apresentar a desigualdade de Harnack parabﾃｳlica. </span> ¥
43 . &nbsp; Seg  --  29/06  --   <span style="color:LightGray"> </span> ¥
44 . &nbsp; Qua  --  01/07  --  <span style="color:LightGray"> Regularidade Parabﾃｳlica </span> ¥
45 . &nbsp; Sex  --  03/07  --  <span style="color:LightGray">   </span> ¥
46 . &nbsp; Seg  --  06/07  --  <span style="color:LightGray">   </span> ¥
47 . &nbsp; Qua  --  08/07  --  <span style="color:LightGray">   </span> ¥
48 . &nbsp; Sex  --  10/07  --  <span style="color:LightGray">   </span> ¥
:end: &nbsp; Sex  --  10/07  --  Fim do Perﾃｭodo. :raised_hands:
---

---

Lista de Tﾃｳpicos

  - Caracterizaﾃｧﾃ｣o de $W^{1,¥infty}$.
  - Desigualdade de Hardy e Teorema de Rademarcher. 
  - 3ﾂｺ Teorema de Existﾃｪncia de soluﾃｧﾃ｣o.
  - Quociente de diferenﾃｧas. Regularidade interior. 
  - Regularidade interior continuaﾃｧﾃ｣o.Regularidade na Fronteira.
  - Princﾃｭpios do Mﾃ｡ximo fraco
  - Princﾃｭpios do Mﾃ｡ximo forte
  - Desigualdade de Harnack
  - Autovalores e Autofunﾃｧﾃｵes 
 

---

# Cronograma Proposto Incialmente

Este foi o programa proposto no inﾃｭcio do perﾃｭdo, que serﾃ｡ mantido aqui para fins de comparaﾃｧﾃ｣o com o cronograma que realmente foi efetivado acima.

<span style="color:standard"> **1. Distribuiﾃｧﾃｵes** </span>

01 . &nbsp; Seg  --  09/03  --  <span style="color:standard"> Apresentaﾃｧﾃ｣o do curso. Preliminares: Teorema de Fubini, espaﾃｧos $L^p$, Desigualdade de Hﾃｶlder. Partiﾃｧﾃ｣o da Unidade. Suporte de funﾃｧﾃｵes. </span> ¥
02 . &nbsp; Qua  --  11/03  --  <span style="color:standard"> Convoluﾃｧﾃ｣o. Desigualdade de Young. Derivaﾃｧﾃ｣o de convoluﾃｧﾃ｣o. </span> ¥
03 . &nbsp; Sex  --  13/03  --  <span style="color:standard"> Funﾃｧﾃｵes regularizantes. Densidade de $C_c^¥infty(¥Omega)$ em $L^p(¥Omega)$. Lema de Du Bois Raymond </span> ¥
04 . &nbsp; Seg  --  16/03  --  <span style="color:standard"> Espaﾃｧos das funﾃｧﾃｵes testes e distribiﾃｧﾃｵes. Convergﾃｪncia. Derivaﾃｧﾃ｣o de distribuiﾃｧﾃｵes. Derivada Fraca. Multiplicaﾃｧﾃ｣o por funﾃｧﾃｵes $C^¥infty$. </span> ¥
---

<span style="color:standard"> **2. Espaﾃｧos de Sobolev** </span>

05 . &nbsp; Qua  --  18/03  --  <span style="color:standard"> Definiﾃｧﾃ｣o de Espaﾃｧos de Sobolev. Banach e reflexivo. $W_0^{k,p}(¥mathbb{R}^d)$. </span> ¥
06 . &nbsp; Sex  --  20/03  --  <span style="color:standard"> Aproximaﾃｧﾃ｣o por Funﾃｧﾃｵes Suaves. Teorema de Friedrichs. Regra da Cadeia. Teorema de Meyers-Serrin. </span> ¥
07 . &nbsp; Seg  --  23/03  --  <span style="color:standard"> Operador Prolongamento.  </span> ¥
08 . &nbsp; Qua  --  25/03  --  <span style="color:standard"> Operador Traﾃｧo. </span> ¥
09 . &nbsp; Sex  --  27/03  --  <span style="color:standard"> Espaﾃｧo das Funﾃｧﾃｵes Hﾃｶlder contﾃｭnuas </span> ¥
10 . &nbsp; Seg  --  30/03  --  <span style="color:standard"> Imersﾃｵes de Sobolev: Teorema de  Gagliardo-Nirenberg-Sobolev. Caso $¥Omega=¥mathbb{R}^d$ e $p¥leq d$. </span> ¥
11 . &nbsp; Qua  --  01/04  --  <span style="color:standard"> Imersﾃｵes de Sobolev: Desigualdade de Morrey. Caso $¥Omega=¥mathbb{R}^d$ e $p>d$. </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  03/04  --  Sexta-feira da Paixﾃ｣o </span> ¥
12 . &nbsp; Seg  --  06/04  --  <span style="color:standard"> Imersﾃｵes de Sobolev: Casos $¥Omega¥subset ¥mathbb{R}^d$. Caso $W_0^{k,p}(¥mathbb{R}^d)$. Desigualdade de Poincarﾃｩ </span> ¥
13 . &nbsp; Qua  --  08/04  --  <span style="color:standard"> Imersﾃｵes Compactas. </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  10/04  --  Feriado Municipal </span> ¥
14 . &nbsp; Seg  --  13/04  --  <span style="color:standard"> Imersﾃｵes Compactas II. </span> ¥
15 . &nbsp; Qua  --  15/04  --  <span style="color:standard"> Caracterizaﾃｧﾃ｣o de $W^{1,¥infty}$. </span> ¥
16 . &nbsp; Sex  --  17/04  --  <span style="color:standard"> Desigualdade de Hardy e Teorema de Rademarcher. </span> ¥
17 . &nbsp; Seg  --  20/04  --  <span style="color:standard"> Espaﾃｧo $H^{-1}(¥Omega)$ </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  21/04  --  Tiradentes </span> ¥
18 . &nbsp; Qua  --  22/04  --  <span style="color:standard"> Aula de Dﾃｺvidas 1 </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  23/04  --  Sﾃ｣o Jorge </span> ¥
<span style="color:red"> 19 . &nbsp; Sex  --  24/04  --  VA 1 (Verificaﾃｧﾃ｣o de Aprendizagem) </span> ¥
---

<span style="color:standard"> **3. Problemas Elﾃｭpticos** </span>

20 . &nbsp; Seg  --  27/04  --  <span style="color:standard"> Operadores Elﾃｭpticos. Definiﾃｧﾃ｣o de Soluﾃｧﾃ｣o Fraca. Teorema de Lax-Milgram. </span> ¥
21 . &nbsp; Qua  --  29/04  --  <span style="color:standard">  1ﾂｺ Teorema de Existﾃｪncia de Soluﾃｧﾃ｣o Fraca. </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  01/05  --  Dia do Trabalho </span> ¥
22 . &nbsp; Seg  --  04/05  --  <span style="color:standard"> Alternativa de Fredholm. 2ﾂｺ Teorema de Existﾃｪncia de soluﾃｧﾃ｣o. </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  06/05  --  Participaﾃｧﾃ｣o em Congresso </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  08/05  --  Participaﾃｧﾃ｣o em Congresso </span> ¥
23 . &nbsp; Seg  --  11/05  --  <span style="color:standard"> 3ﾂｺ Teorema de Existﾃｪncia de soluﾃｧﾃ｣o. </span> ¥
24 . &nbsp; Qua  --  13/05  --  <span style="color:standard"> Quociente de diferenﾃｧas. Regularidade interior. </span> ¥
25 . &nbsp; Sex  --  15/05  --  <span style="color:standard"> Regularidade interior continuaﾃｧﾃ｣o.Regularidade na Fronteira. </span> ¥
26 . &nbsp; Seg  --  18/05  --  <span style="color:standard"> Princﾃｭpios do Mﾃ｡ximo fraco  </span> ¥
27 . &nbsp; Qua  --  20/05  --  <span style="color:standard"> Princﾃｭpios do Mﾃ｡ximo forte  </span> ¥
28 . &nbsp; Sex  --  22/05  --  <span style="color:standard"> Desigualdade de Harnack </span> ¥
29 . &nbsp; Seg  --  25/05  --  <span style="color:standard"> Autovalores e Autofunﾃｧﾃｵes </span> ¥
30 . &nbsp; Qua  --  27/05  --  <span style="color:standard"> Aula de Dﾃｺvidas 2 </span> ¥
<span style="color:red"> 31 . &nbsp; Sex  --  29/05  --  VA 2 (Verificaﾃｧﾃ｣o de Aprendizagem) </span> ¥
---

<span style="color:standard"> **4. Problemas Parbﾃｳlicos e Hiperbﾃｳlicos** </span>

32 . &nbsp; Seg  --  01/06  --  <span style="color:standard"> Distribuiﾃｧﾃｵes Vetoriais </span> ¥
33 . &nbsp; Qua  --  03/06  --  <span style="color:standard"> Problemas Parabﾃｳlicos de segunda ordem. Definiﾃｧﾃ｣o de soluﾃｧﾃ｣o fraca. Aproximaﾃｧﾃｵes de Galerkin.  </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  04/06  --  Corpus Christ </span> ¥
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  05/06  --  Ponto Facultativo </span> ¥
34 . &nbsp; Seg  --  08/06  --  <span style="color:standard"> Desigualdade de Energia </span> ¥
35 . &nbsp; Qua  --  10/06  --  <span style="color:standard"> Existﾃｪncia e Unicidade de soluﾃｧﾃｵes. </span> ¥
36 . &nbsp; Sex  --  12/06  --  <span style="color:standard"> Regularidade de Soluﾃｧﾃｵes </span> ¥
37 . &nbsp; Seg  --  15/06  --  <span style="color:standard"> Princﾃｭpio do Mﾃ｡ximo fraco parabﾃｳlico </span> ¥
38 . &nbsp; Qua  --  17/06  --  <span style="color:standard"> Desigualdade de Harnack parabﾃｳlica </span> ¥
39 . &nbsp; Sex  --  19/06  --  <span style="color:standard"> Princﾃｭpios do Mﾃ｡ximo forte parabﾃｳlico </span> ¥
40 . &nbsp; Seg  --  22/06  --  <span style="color:standard"> Problemas Hiperbﾃｳlicos de segunda ordem. Definiﾃｧﾃ｣o de soluﾃｧﾃ｣o fraca. Aproximaﾃｧﾃｵes de Galerkin. </span> ¥
41 . &nbsp; Qua  --  24/06  --  <span style="color:standard">  Desigualdade de Energia </span> ¥
42 . &nbsp; Sex  --  26/06  --  <span style="color:standard"> Existﾃｪncia e Unicidade de soluﾃｧﾃｵes. </span> ¥
43 . &nbsp; Seg  --  29/06  --  <span style="color:standard"> Regularidade de Soluﾃｧﾃｵes </span> ¥
44 . &nbsp; Qua  --  01/07  --  <span style="color:standard"> Velocidade de Propagraﾃｧﾃ｣o finita </span> ¥
45 . &nbsp; Sex  --  03/07  --  <span style="color:standard"> Aula de Dﾃｺvidas 3 </span> ¥
<span style="color:red"> 46 . &nbsp; Seg  --  06/07  --  VA 3 (Verificaﾃｧﾃ｣o de Aprendizagem) </span> ¥
---

 

47 . &nbsp; Qua  --  08/07  --  <span style="color:standard"> Aula reservada para reacomodaﾃｧﾃ｣o do calendﾃ｡rio </span> ¥
48 . &nbsp; Sex  --  10/07  --  <span style="color:standard">  --  </span> ¥
:end: &nbsp; Sex  --  10/07  --  Fim do Perﾃｭodo. :raised_hands:
---



# Referﾃｪncias {#sec-ref}

-  Brezis, Haim. Functional analysis, Sobolev spaces and partial differential equations. Springer, New York-London, 2011.

- Evans, Lawrence C. Partial differential equations, volume 19. American Mathematical Society, Providence, Rhode Island, 2010.

-  Kesavan, S. Topics in Functional Analysis and Applications, volume 52. New Age International Ltd, New Delhi, 2015.


