---
title: GAAL RCN00075 -- 2025-1
number-sections: true
bibliography: ../biblio.bib
csl: aims-mathematics.csl
nocite: |
  @*

format:
  html:
    toc: true
from: markdown+emoji
---

# Informações Básicas

- **Início e Fim do Período:** 24/03/2025 a 26/07/2025.

-  **Horário e sala:** \
2ª (16h às 18h) e 3ª (14h às 16h) **Sala 02** -- **ICT**\
confira no [Quadro de Alocação de salas do ICT](http://200.159.243.161/index.php/segunda/)  

- **Material a ser utilizado**

- [Slides](https://reginaldodr.github.io/gaal-2023/gaal.pdf)

- [Anotações das aulas]

- [Livro GAAL -- Reginaldo Santos -- UFMG](../gaalt0.pdf)

- [Lista Exercícios Poole (2004)](../lista-gaal-poole-2004.pdf)

- [Lista de Exercícios de GA](../lista-exercicios-GA.pdf)

- [Provas antigas](../provas/)

 


-  **Ementa:** Busque por RCN00075 em [quadro de horários](https://app.uff.br/graduacao/quadrodehorarios/):\
MATRIZES E SISTEMAS LINEARES. DETERMINANTES. VETORES NO PLANO E NO ESPAÇO. RETAS E PLANOS. ESPAÇO $\mathbb{R}^n$. AUTOVALORES E AUTOVETORES DE UMA MATRIZ. DIAGONALIZAÇÃO DE MATRIZES. RECONHECIMENTO DE CÔNICAS.

- **Monitoria:** 

# Apresentação do Curso

Este curso é constituído de dois módulos:

1. Matrizes, Sistemas lineares, Determinates e Geometria Analítica;
2. Álgebra Linear no $\mathbb{R}^n$.


Usaremos como livro texto as referências [@poole] e [@santosufmg]. **A primeira está disponível para empréstimo na Biblioteca do campus** -- [BRO](https://bibliotecas.uff.br/bro/). A segudna pode ser baixada [aqui](../gaalt0.pdf). <span style="color:red">  É altamente recomendado que vocês consultem este material, de preferência, o livro físico.</span>

As demais referência contidas na @sec-ref serão usadas como material auxiliar ao longo do curso.\


# Avaliação

A avaliação será feita mediante **Duas Provas Escritas**. A nota final será a média aritmética elas.


## Sobre as Provas

- **Fazem parte dos critério de avaliação:**
   1. Clareza, organização, rigor e detalhes.
   2. Fundamentação das soluções no conteúdo ensinado.
   3. Interpretação correta das questões.
   4. Questão com várias soluções será anulada.
   5. Resposta correta com solução errada será anulada.

- **Instruções:**
    - Proibido compartilhar material.
    - Só é permitida a saída após entrega definitiva da prova, ou seja, não é permitido ir ao banheiro ou beber água. A prova tem duração de no máximo 2 horas.
    - É permitida a **consulta a material** (livros, notas de aula, caderno, apostilas e etc.)  e uso de dispositivo computacional, como calculadora científica, ambos **sem acesso a internet**.
    - Fraude detectada, mesmo depois, zera a nota.

## Segunda Chamada

O Art. 98 do  [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) garante ao aluno  o direito a uma avaliação de **Segunda Chamada (VR)**, <span style="color:red">**sem a necessidade de justificativa!**</span> Portanto, aquele aluno que **não puder ou não quiser** fazer uma das provas, poderá faltar que seu direito à Segunda Chamada será garantido.

O conteúdo da **Segunda Chamada** será <span style="color:red">toda a matéria do semestre.</span>


::: {.callout-warning}
## Importante

Como **não há a necessidade de justificar a falta nas avaliações** para ter o direito à Segunda Chamada garantido, alguns alunos usam este direito para fazer a Segunda Chamada quando não se sentem suficientemente preparados para alguma das avaliações. 

Por conta disso, o aluno que estiver em dúvida entre fazer a prova ou a Segunda chamada, poderá comparecer no dia da prova e tentar fazê-la. Caso não se sinta preparado, poderá desistir e ainda terá o direito a fazer a Segunda Chamada. Aqueles que permanecerem e entregarem definitivamente a prova não terão o direito à Segunda Chamada.
:::

## Verificação Suplementar

Em concordância com o [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) em seu Art. 99, a **Verificação Suplementar (VS)** é vetada aos discentes já aprovados e é **obrigatória** para aqueles que tenham obtido média parcial entre 4,0 e 5,9, sendo esses dois limites incluídos.


# Listas de Exercícios

Abaixo seguem os execícios das referências @poole e @santosufmg e, também os da [lista de GA plana](../lista-exercicios-GA.pdf), que devem ser feitos a fim de se preparar para a avaliação escrita. Os exercícios marcado com o símbolo SAC no livro, devem ser feitos usando uma ferramenta computacional, como por exemplo o python.

Veja as listas em [Material Básico](../gaal.qmd).


- **Matrizes, Sistemas Lineares e Determinantes**\
@poole **§ 3.1 (Matrizes):** 1, 11, 13, 17, 35.\
@poole **§ 3.2 (Matrizes):** 1, 4, 23.\
@poole **§ 2.2 (Sistemas Lineares):** 1, 3, 5, 15, 17, 27, 29, 31.\
@poole **§ 2.3 (Resolução de Sistemas Lineares):** 9, 11,  13, 23, 25, 27, 29, 31, 39, 41, 43, 47.\
@poole **§ 3.4 (Matriz Inversa):** 49, 53, 57, 51, 55, 45, 20, 21.\
@poole **§ 4.3 (Determinantes):** 1, 3, 5, 7, 9, 13, 27, 29, 33, 47, 49, 51.\

- **Geometria Analítica** \
GA em $\mathbb{R}^2$ fazer  os exercícios desta [lista de GA plana](../lista-exercicios-GA.pdf)\
**(Coordenadas e distância em $\mathbb{R}^2$):** 1.1 (a,b,c), 1.3, 1.8.\
**(Vetores e Produto escalar em $\mathbb{R}^2$):** 2.1 (a), 2.2, 2.5(b), 2.6 (a,b), 2.7, 2.10.\
**(Equação da Reta):** 4.2(a,b), 4.5, 4.6, 4.9, 4.18.\
GA em $\mathbb{R}^3$\
@santosufmg **3.3 (Produtos Vetorias):** 2, 3, 4, 5, 7.\
@poole **§ 1.4 (Retas e Planos):** 3, 5, 7,  11, 15, 17, 21, 23.\
@santosufmg **4.3 (Distância de ponto a reta):** 8, 9.\

- **Álgebra Linear**\
@poole **§ 1.2 (Vetores em $\mathbb{R}^n$):** 5, 11, 12, 14, 17.\
@poole **§ 1.3 (Produto Escalar em $\mathbb{R}^n$):** 1, 3, 5, 7, 9, 17, 19, 21, 23, 27, 29, 39, 46, 47, 51.\
@santosufmg **5.1 (LI e LD):** 1, 3, 4, 8.\
@poole **§ 3.5 (Subespaço,Base e Dimensão):** 13, 15, 23, 26, 27, 28, 43.\
@santosufmg **6.1 (Autovetores):** 1, 2, 3, 5, 6, 7.\
@poole **§ 4.5 (Diagonalização):** 11, 13, 15, 17, 21, 25, 27.\ 

:construction: Em construção... 

# Referências {#sec-ref}


::: {#refs}
:::

# Cronograma Efetivado {#sec-crono}


---


# Crongrama Porposto Inicialmente

Este foi o programa proposto no início do perído, que será mantido aqui para fins de comparação com o cronograma que realmente foi efetivado acima.

**1. Matrizes, Sistemas lineares, Determinates e Geometria Analítica;**

01 . &nbsp; Seg  --  24/03  --  <span style="color:standard"> Apresentação do curso. Coordenadas cartesianas no plano. Espaço Vetorial $\mathbb{R}^2$.  Representação Geométrica. Norma. Regra do paralelogramo. </span> \
02 . &nbsp; Ter  --  25/03  --  <span style="color:standard"> O espaço vetorial $\mathbb{R}^3$ e representação geométrica. O espaço vetorial $\mathbb{R}^n$. Norma e vetor unitário. Combinação Linear. </span> \
03 . &nbsp; Seg  --  31/03  --  <span style="color:standard"> Matrizes: definição, operações e propriedades </span> \
04 . &nbsp; Ter  --  01/04  --  <span style="color:standard"> Matrizes identidade e transposta. Operações usando o sympy. Produto escalar no $\mathbb{R}^n$. Ângulo entre vetores. Produto escalar usando o sympy. </span> \
05 . &nbsp; Seg  --  07/04  --  <span style="color:standard"> Fórmula do ângulo. Equação paramétrica da reta. </span> \
06 . &nbsp; Ter  --  08/04  --  <span style="color:standard"> Equações Cartesianas da Reta em $\mathbb{R}^2$. Equação cartesina do Plano em $\mathbb{R}^3$. Sistemas de Equações Lineares. Operações Elementares. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  10/04  --  Feriado Municipal </span> \
07 . &nbsp; Seg  --  14/04  --  <span style="color:standard"> Escalonamento </span> \
08 . &nbsp; Ter  --  15/04  --  <span style="color:standard"> Posto de uma matriz. Variáveis livres. Usando sympy para resolver sistemas lineares.Método de Gauss-Jordan. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  18/04  --  Sexta-feira da Paixão </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  21/04  --  Tiradentes </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  22/04  --  Não Haverá Aula </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  23/04  --  São Jorge </span> \
09 . &nbsp; Seg  --  28/04  --  <span style="color:standard"> Equação paramétrica da reta. Equações Cartesianas da Reta em $\mathbb{R}^2$. </span> \
10 . &nbsp; Ter  --  29/04  --  <span style="color:standard"> Equação cartesina do Plano em $\mathbb{R}^3$. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  01/05  --  Dia do Trabalho </span> \
11 . &nbsp; Seg  --  05/05  --  <span style="color:standard"> Definição de Produto Vetorial. Propriedades do Produto Vetorial. </span> \
12 . &nbsp; Ter  --  06/05  --  <span style="color:standard"> Produto Misto. Volumes do Paralelepípedo. Distâncias: entre Ponto e Plano </span> \
13 . &nbsp; Seg  --  12/05  --  <span style="color:standard"> Distância de ponto à Reta. Distâncias: Entre Retas, entre reta e Plano </span> \
14 . &nbsp; Ter  --  13/05  --  <span style="color:standard"> Aula de Exercícios 1 </span> \
<span style="color:red"> 15 . &nbsp; Seg  --  19/05  --  1ª Prova </span> \
---

**2. Álgebra Linear no $\mathbb{R}^n$**

16 . &nbsp; Ter  --  20/05  --  <span style="color:standard"> O espaço vetorial $\mathbb{R}^n$. Norma e vetor unitário. Produto escalar no $\mathbb{R}^n$. Produto escalar usando o sympy. </span> \
17 . &nbsp; Seg  --  26/05  --  <span style="color:standard"> Dependência e Independência Linear </span> \
18 . &nbsp; Ter  --  27/05  --  <span style="color:standard"> Posição Relativa de retas e planos. Subespaço vetorial. </span> \
19 . &nbsp; Seg  --  02/06  --  <span style="color:standard"> Subespaço gerado. Base e Dimensão </span> \
20 . &nbsp; Ter  --  03/06  --  <span style="color:standard"> Núcleo de uma matriz. Espaço linha e Espaço coluna. </span> \
21 . &nbsp; Seg  --  09/06  --  <span style="color:standard"> Como obter bases de subespaços. Definição de Autovetores e Autovalores  </span> \
22 . &nbsp; Ter  --  10/06  --  <span style="color:standard"> Autoespaços. Matrizes semelhantes. Diagonalização de Matrizes. </span> \
23 . &nbsp; Seg  --  16/06  --  <span style="color:standard"> Exemplos de Diagonalização. Diagonalizando com sympy. Projeção Ortogonal. Bases Ortogonais e Ortonormais. </span> \
24 . &nbsp; Ter  --  17/06  --  <span style="color:standard"> Processo de Ortogonalização de Gram-Schimidt. Matrizes Ortogonais. Teorema Espectral. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  19/06  --  Corpus Christ </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  20/06  --  Ponto Facultativo </span> \
25 . &nbsp; Seg  --  23/06  --  <span style="color:standard"> Completamento de Quadrados. Cônicas. Equações reduzidas da Elipse, hipérbole e Parábola. </span> \
26 . &nbsp; Ter  --  24/06  --  <span style="color:standard"> Translação de Cônicas. Formas Quadráticas e Teorema dos Eixos Principais em $\mathbb{R}^2$ </span> \
27 . &nbsp; Seg  --  30/06  --  <span style="color:standard"> Rotação de cônicas. </span> \
28 . &nbsp; Ter  --  01/07  --  <span style="color:standard"> Aula de Exercícios 2 </span> \
<span style="color:red"> 29 . &nbsp; Seg  --  07/07  --  2ª Prova </span> \
---

**Provas Finais**

<span style="color:red"> 30 . &nbsp; Ter  --  08/07  --  2ª Chamada </span> \
<span style="color:red"> 31 . &nbsp; Seg  --  14/07  --  VS </span> \
32 . &nbsp; Ter  --  15/07  --  <span style="color:standard">  --  </span> \
33 . &nbsp; Seg  --  21/07  --  <span style="color:standard">  --  </span> \
34 . &nbsp; Ter  --  22/07  --  <span style="color:standard">  --  </span> \
:end: &nbsp; Sáb  --  26/07  --  Fim do Período. :raised_hands:
---

