---
title: CÁLCULO II RCN00020 -- 2023-2
number-sections: true
bibliography: biblio.bib
csl:  aims-mathematics.csl
nocite: |
  @*
  
format:
  html:
    toc: true
from: markdown+emoji
---
# Informações Básicas

-  **Horário e sala:** 4ª e 6ª 16h -- 18h -- **sala 04 -- IHS (prédio alugado)**\
confira no [Quadro de Alocação de salas do IHS](http://200.159.243.2:10032/home/index_simples)

-  **Atendimento:** sala 104 -- IHS (prédio alugado)

- [Material a ser utilizado](calculoII.qmd)

-  **Ementa:** Busque por RCN00020 em [quadro de horários](https://app.uff.br/graduacao/quadrodehorarios/):\
INTEGRAL DEFINIDA. TÉCNICAS DE INTEGRAÇÃO. INTEGRAIS IMPRÓPRIAS. EQUAÇÕES DIFERENCIAIS 
DE  PRIMEIRA  ORDEM.  EQUAÇÕES  DIFERENCIAIS  DE  SEGUNDA  ORDEM.  EQUAÇÕES  DIFERENCIAIS
LINEARES DE ORDEM N.



# Apresentação do Curso

Este curso é constituído de dois grandes módulos: **Cálculo Integral** e **Equações Diferenciais Ordinárias (EDO)**

Usaremos o **Classroom** como Ambiente Virtual de Aprendizagem (AVA), onde serão postadas as notas e realizadas as discussões e comunicações.


Para o módulo de **Cálculo Integral**, usaremos com livro texto a referência [@stewart1], e para o módulo de **EDO** usaremos [@Boyce]. **Essas duas referências estão disponíveis para empréstimo na Biblioteca do campus** -- [BRO](https://bibliotecas.uff.br/bro/). <span style="color:red">É altamente recomendado que vocês consultem este material, de preferência, o livro físico.</span>

As demais referência contidas na @sec-ref serão usadas como material auxiliar ao longo do curso.\


# Avaliação

A avaliação será feita ao fim de cada módulo:

- **Cálculo Integral:** Um prova, valendo 8 pontos, e um trabalho, valendo 2 ponto.

- **EDO:** Uma única prova, valendo 10 pontos.

A nota final será a média aritmética entre as avaliações de cada módulo, isto é, 
$$N=\frac{P_1+T_1+P_2}{2},$$
onde $P_1$ é a nota da primeira prova, $T_1$ é a nota do trabalho e $P_2$ é a nota da segunda prova. Veja no cronograma, @sec-crono abaixo, as datas destas avaliações. 

## Sobre as Provas

As duas provas serão **escritas e com consulta** a qualquer material impresso ou manuscrito (livros, notas de aula, caderno, apostilas e etc.). <span style="color:red"> Não será permitido o uso de dispositivos eletrônicos com acesso à internet (tablets, celulares e etc).</span> Será permitido o uso de calculadora científica.


## Sobre o Trabalho

- Tema: Integrais Impróprias e Teste da Comparação. 
    - **Referências:** Seção 7.8 da referência [@stewart1] . Videoaulas: [Integrais Impróprias](https://youtu.be/UqpxSNmyGPI) e [Testes de Convergência ](https://youtu.be/e-SFGQVi-ys)
- Deverá ser feito em grupos de 4 a 5 integrantes.
- Deverá ser manuscrito.
- Deverá ser entregue no dia da Primeira Prova. 
- Haverá na primeira prova uma questão sobre o trabalho.

## Segunda Chamada

O Art. 98 do  [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) garante ao aluno  o direito a uma avaliação de **Segunda Chamada (VR)**, <span style="color:red">sem a necessidade de justificativa!</span> Portanto, aquele aluno que **não puder ou não quiser** fazer uma das provas, poderá faltar que seu direito à Segunda Chamada será garantido.

A Segunda Chamada de todas as avaliações será feita no mesmo dia (veja data na @sec-crono). Será elaborada uma prova de Segunda Chamada para cada avaliação regular do curso, no mesmo nível destas avaliações. 

Contudo, cabe ressaltar que, de acordo com o mesmo artigo, a Segunda Chamada **substituirá uma, e somente uma,** das avaliações que tenha faltado. Portanto, se o aluno faltar a mais de uma avaliação, no dia da Segunda Chamada poderá escolher qual fará, mas só poderá fazer uma das avaliações.


::: {.callout-warning}
## Importante

Como **não há a necessidade de justificar a falta nas avaliações** para ter o direito à Segunda Chamada garantido, alguns alunos usam este direito para fazer a Segunda Chamada quando não se sentem suficientemente preparados para alguma das avaliações. 

Por conta disso, os primeiros 30 minutos de cada  avaliação serão reservados para o aluno decidir melhor se quer fazer a prova ou deixará para fazer a Segunda Chamada. Isto é, o aluno que estiver em dúvida entre fazer a prova ou a Segunda chamada, poderá comparecer no dia da prova e tentar fazê-la. Caso não se sinta preparado, dentro dos  primeiros 30 minutos, poderá desistir e ainda terá o direito a fazer a Segunda Chamada. Aqueles que permanecerem após os 30 minutos não terão mais o direito à Segunda Chamada.
:::

## Verificação Suplementar

Em concordância com o [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) em seu Art. 99, a **Verificação Suplementar (VS)** é vetada aos discentes já aprovados e é **obrigatória** para aqueles que tenham obtido média parcial entre 4,0 e 5,9, sendo esses dois limites incluídos.


# Listas de Exercícios

**Integral**: Abaixo seguem os execícios da referência @stewart1 que devem ser feitos. Os exercícios marcado com o símbolo SAC no livro, devem ser feitos usando uma ferramenta computacional, como por exemplo o python.

§ 5.1: 11, 15.\
§ 5.2: 5, 33, 35, 37, 47, 49, 53.\
§ 5.3: 7, 9, 17, 19, 23, 27, 29, 35, 39, 53, 55.\
§ 5.4: 5, 9, 11, 17, 29, 31, 35, 37, 41, 61.\
§ 5.5: 7, 9, 19, 21, 23, 27, 35, 53, 57, 59, 63, 74, 76, 78, 81.\
§ 6.1: 1, 3, 5, 9, 13, 23, 24, 29, 39, 49, 51, 53.\
§ 7.1: 3, 5, 7, 9, 15, 17, 23, 25, 27, 33, 44, 47.\
§ 7.2: 3, 7, 17, 21, 25, 29, 31, 43, 45, 56, 57, 66, 70.\
§ 7.3: 5, 7, 11, 13, 17, 23, 25, 35, 41.\
§ 7.4: 7, 9, 11, 13, 15, 17, 63, 65, 67.\
Leia a seção 7.5 (Estratégias de Integração)\
§ 7.5: 1, 3, 5, 7, 13, 15, 17, 23, 25, 27, 33, 41, 45, 63.\
§ 6.2: 1, 3, 5,19, 21, 39, 45, 51, 67.\
§ 6.3: 5, 7, 9, 15, 19, 43, 46.\
§ Em construção

**EDO**: Abaixo seguem os execícios da referência @Boyce que devem ser feitos. A distribuição está dada por seção. Os exercícios marcado com o símbolo🖱️​ no livro, devem ser feitos usando uma ferramenta computacional, como por exemplo o python.

§ 1.1: 1, 5, 11, 13, 22, 23.\
§ 1.3: 1, 2, 5, 6, 8, 9, 11, 15.\
§ 2.2: 1, 6, 8, 10, 12 .\
§ 2.3: 12, 13, 16, 21.\
§ 2.1: 1, 4, 5, 6, 7, 9, 13, 15, 16, 17,18.\
§ 2.4: 1, 2, 5, 7, 11, 27, 28.\
§ 3.1: 1-4, 9-12, 20, 21, 22.\
§3.2: 1,2, 21, 22, 23, 25.\
§3.4: 7-10, 17-20, 25.\
§3.5: 1-4, 11-14, 15, 18.\
§3.6: 1-5, 8, 14, 17.\
§3.7: 5-7, 13, 14.\
§3.8: 6, 9, 11, 14, 17, 27.

# Referências {#sec-ref}


::: {#refs}
:::



# Cronograma {#sec-crono}

A seguir temos a proposta de cronograma para este curso. Esta proposta pode sofrer pequenas alterações ao longo do curso que, caso ocorram, serão comunicadas aos alunos. **Cabe ressaltar que o semestre se encerra no dia 20/12, neste caso, é aconselhado que fiquem disponíveis até esta data.**



## Cronograma Efetivado

01 . &nbsp; Qua  --  30/08  -- Apresentação. Um pouco sobre a História do Cálculo. Método da Exaustão. Notação Sigma. \
02 . &nbsp; Sex  --  01/09  --   Resolução do Para :house: . Somas de Riemann e Integral Definida. Distância percorrida. 
**Próxima Aula:** resolver Para :house: 2 e 3.\
03 . &nbsp; Qua  --  06/09  -- Resolução do Para :house: .  Propriedades da Integral. Teorema Fundamental do Cálculo e integrais elementares. **Próxima Aula:** resolver Para :house: 4 e 5.  \
<span style="color:orange"> XX . &nbsp; Qui  --  07/09  --  Independência </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  08/09  --  Facultativo </span> \
04 . &nbsp; Qua  --  13/09  -- Resolução dos Para :house: 4 e 5. Funções não-integráveis. Integral indefinida. Queda livre de corpos. Regra da substituição. **Próxima Aula:** resolver Para :house: 6. \
05 . &nbsp; Sex  --  15/09  -- Resolução do Para :house: 6. Cresc. populacional Malthusiano. Integral de Funções Pares e Ímpares. **Próxima Aula:** resolver Para :house: 7 e 8. \
06 . &nbsp; Qua  --  20/09  -- Resolução Para :house: 7 e 8.  Áreas entre curvas. Exemplo 1. Exemplo 2 (terminar).\
07 . &nbsp; Sex  --  22/09  --  Conclusão do Exemplo 2. Integração por Partes. Integração por substituição Trigonométrica - Exemplo 1. **Próxima Aula:** resolver Para :house: 9 e 10.\
08 . &nbsp; Qua  --  27/09  --  Resolução dos Para :house: 9 e 10. Revisão do Exemplo 1 da aula anterior. Usamos substituição trigonométrica para provar a fórmula da área de um círculo.\
09 . &nbsp; Sex  --  29/09  --  <span style="color:LightGray">  Integração de funções racionais: frações parciais. Aplicação ao crescimento populacional logístico. Cálculo de volumes pelo método dos discos </span> \
10 . &nbsp; Qua  --  04/10  --  <span style="color:LightGray"> Volume por cascas cilíndricas, Comprimento de Curvas </span> \
11 . &nbsp; Sex  --  06/10  --  <span style="color:LightGray"> Integrais Impróprias: Limites Infinitos </span> \
<span style="color:red"> 12 . &nbsp; Qua  --  11/10  --  1ª Prova </span> \
<span style="color:orange"> XX . &nbsp; Qui  --  12/10  --  Nossa Senhora Aparecida </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  13/10  --  Facultativo </span> \
<span style="color:orange"> XX . &nbsp; Qua  --  18/10  --  Semana Nacional de Ciência e Tecnologia </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  20/10  --  Semana Nacional de Ciência e Tecnologia </span> \
13 . &nbsp; Qua  --  25/10  --  <span style="color:LightGray"> EDOs: modelos (populacionais, massa-mola, pêndulo, queda livre com resistência do ar) </span> \
14 . &nbsp; Sex  --  27/10  --  <span style="color:LightGray"> Classificação e solução. Campos direcionais. Equações Separáveis 1ª ordem, EDO 1ª ordem linear </span> \
<span style="color:orange"> XX . &nbsp; Sáb  --  28/10  --  Servidor Público </span> \
15 . &nbsp; Qua  --  01/11  --  <span style="color:LightGray"> Equações Exatas. Teorema de Existência e Unicidade de Soluções para EDO de 1ª ordem lineares </span> \
<span style="color:orange"> XX . &nbsp; Qui  --  02/11  --  Finados </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  03/11  --  Facultativo </span> \
16 . &nbsp; Qua  --  08/11  --  <span style="color:LightGray"> EDO’s 2ª ordem lineares. Teorema de Existência e Unicidade. Soluções Fundamentais. Wronskiano </span> \
17 . &nbsp; Sex  --  10/11  --  <span style="color:LightGray"> Oscilações mecânicas livres com amortecimento. EDO 2ª ord. linear homogênea com coef. constantes - caso raízes distintas </span> \
<span style="color:orange"> XX . &nbsp; Qua  --  15/11  --  Proclamação da República </span> \
18 . &nbsp; Sex  --  17/11  --  <span style="color:LightGray"> EDO linear homogênea com coeficientes constantes - caso raízes reais iguais. Revisão de números complexos. Caso raízes complexas e fórmula de Euler </span> \
<span style="color:orange"> XX . &nbsp; Seg  --  20/11  --  Consciência Negra </span> \
19 . &nbsp; Qua  --  22/11  --  <span style="color:LightGray"> Método dos coeficientes a determinar </span> \
20 . &nbsp; Sex  --  24/11  --  <span style="color:LightGray"> Método da variação dos Parâmetros </span> \
<span style="color:red"> 21 . &nbsp; Qua  --  29/11  --  2ª Prova </span> \
<span style="color:red"> 22 . &nbsp; Sex  --  01/12  --  2ª Chamada </span> \
<span style="color:red"> 23 . &nbsp; Qua  --  06/12  --  VS </span> \
24 . &nbsp; Sex  --  08/12  --  <span style="color:LightGray">  --  </span> \
25 . &nbsp; Qua  --  13/12  --  <span style="color:LightGray">  --  </span> \
26 . &nbsp; Sex  --  15/12  --  <span style="color:LightGray">  --  </span> \
27 . &nbsp; Qua  --  20/12  --  <span style="color:LightGray">  --  </span> \

---

## Crongrama Porposto Inicialmente

Este foi o programa proposto no início do perído, que será mantido aqui para fins de comparação com o cronograma que realmente foi efetivado acima.

01 . &nbsp; Qua  --  30/08  --  Apresentação. Um pouco sobre a História do Cálculo. Método da Exaustão. Notação Sigma. \
02 . &nbsp; Sex  --  01/09  --  Somas de Riemann e Integral Definida. Distância percorrida \
03 . &nbsp; Qua  --  06/09  --  Propriedades da Integral. Teorema Fundamental do Cálculo e integrais elementares \
<span style="color:orange"> XX . &nbsp; Qui  --  07/09  --  Independência </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  08/09  --  Facultativo </span> \
04 . &nbsp; Qua  --  13/09  --  Funções não-integráveis. Integral indefinida \
05 . &nbsp; Sex  --  15/09  --  Integração por Substituição e Aplicações (queda livre, cresc. populacional, carbono 14) \
06 . &nbsp; Qua  --  20/09  --  Áreas entre curvas \
07 . &nbsp; Sex  --  22/09  --  Integração por Partes. Integração por substituição Trigonométrica \
08 . &nbsp; Qua  --  27/09  --  Integração de funções racionais: frações parciais. Aplicação ao crescimento populacional logístico \
09 . &nbsp; Sex  --  29/09  --  Cálculo de volumes pelo método dos discos \
10 . &nbsp; Qua  --  04/10  --  Volume por cascas cilíndricas, Comprimento de Curvas \
11 . &nbsp; Sex  --  06/10  --  Integrais Impróprias: Limites Infinitos \
<span style="color:red"> 12 . &nbsp; Qua  --  11/10  --  1ª Prova </span> \
<span style="color:orange"> XX . &nbsp; Qui  --  12/10  --  Nossa Senhora Aparecida </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  13/10  --  Facultativo </span> \
<span style="color:orange"> XX . &nbsp; Qua  --  18/10  --  Semana Nacional de Ciência e Tecnologia </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  20/10  --  Semana Nacional de Ciência e Tecnologia </span> \
13 . &nbsp; Qua  --  25/10  --  EDOs: modelos (populacionais, massa-mola, pêndulo, queda livre com resistência do ar) \
14 . &nbsp; Sex  --  27/10  --  Classificação e solução. Campos direcionais. Equações Separáveis 1ª ordem, EDO 1ª ordem linear \
<span style="color:orange"> XX . &nbsp; Sáb  --  28/10  --  Servidor Público </span> \
15 . &nbsp; Qua  --  01/11  --  Equações Exatas. Teorema de Existência e Unicidade de Soluções para EDO de 1ª ordem lineares \
<span style="color:orange"> XX . &nbsp; Qui  --  02/11  --  Finados </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  03/11  --  Facultativo </span> \
16 . &nbsp; Qua  --  08/11  --  EDO’s 2ª ordem lineares. Teorema de Existência e Unicidade. Soluções Fundamentais. Wronskiano \
17 . &nbsp; Sex  --  10/11  --  Oscilações mecânicas livres com amortecimento. EDO 2ª ord. linear homogênea com coef. constantes - caso raízes distintas \
<span style="color:orange"> XX . &nbsp; Qua  --  15/11  --  Proclamação da República </span> \
18 . &nbsp; Sex  --  17/11  --  EDO linear homogênea com coeficientes constantes - caso raízes reais iguais. Revisão de números complexos. Caso raízes complexas e fórmula de Euler \
<span style="color:orange"> XX . &nbsp; Seg  --  20/11  --  Consciência Negra </span> \
19 . &nbsp; Qua  --  22/11  --  Método dos coeficientes a determinar \
20 . &nbsp; Sex  --  24/11  --  Método da variação dos Parâmetros \
<span style="color:red"> 21 . &nbsp; Qua  --  29/11  --  2ª Prova </span> \
<span style="color:red"> 22 . &nbsp; Sex  --  01/12  --  2ª Chamada </span> \
<span style="color:red"> 23 . &nbsp; Qua  --  06/12  --  VS </span> \
24 . &nbsp; Sex  --  08/12  --   --  \
25 . &nbsp; Qua  --  13/12  --   --  \
26 . &nbsp; Sex  --  15/12  --   --  \
27 . &nbsp; Qua  --  20/12  --   -- 