---
title: CÁLCULO II RCN00020 -- 2024-2
number-sections: true
bibliography: biblio.bib
csl:  aims-mathematics.csl
nocite: |
  @*
  
format:
  html:
    toc: true
from: markdown+emoji
---
# Informações Básicas
- **Início e Fim do Período:** 23/09/2024 a 06/02/2024 
    - Recesso fim de ano: 23/12/2024 a 05/01/2025

-  **Horário e sala:** \
2ª (14h às 16h) **Sala 06** -- **IHS (prédio alugado)**\
3ª (16h às 18h) **Sala 04** -- **IHS (prédio alugado)**\
confira no [Quadro de Alocação de salas do IHS](http://159.112.185.66/home/index_simples)  [acesso por celular](http://159.112.185.66/home_externo/index)

-  **Atendimento:** Quintas-feiras das 16h-18h -- sala 104 -- IHS (prédio alugado) -- Enviar [email](mailto:reginaldodr@id.uff.br) caso queira agendar outro horário.

- **Material a ser utilizado**

    - [Slides-integral](https://reginaldodr.github.io/calculo2/integral-resumido/integral.pdf)

    - [Slides-EDO](https://reginaldodr.github.io/calculo2/edo-2024/edo.pdf)
    
    - [Anotações das aulas](https://mega.nz/folder/yFVUwSSQ#c0TXDpxhIl_aeAKLViskRA)
    
    - [Provas antigas](provas/)
    
    - [Outros Materiais](calculoII.qmd)

    
-  **Ementa:** Busque por RCN00020 em [quadro de horários](https://app.uff.br/graduacao/quadrodehorarios/):\
INTEGRAL DEFINIDA. TÉCNICAS DE INTEGRAÇÃO. INTEGRAIS IMPRÓPRIAS. EQUAÇÕES DIFERENCIAIS 
DE  PRIMEIRA  ORDEM.  EQUAÇÕES  DIFERENCIAIS  DE  SEGUNDA  ORDEM.  EQUAÇÕES  DIFERENCIAIS
LINEARES DE ORDEM N.

- **Monitoria:** Aguardando o processo seletivo.

# Apresentação do Curso

Este curso é constituído pelos seguintes módulos

1. **Cálculo Integral**
    1. A integral e técnicas de integração;
    2. Aplicações da Integral;
2. **Equações Diferenciais Ordinárias (EDO)**
    1. EDOs de 1ª ordem;
    2. EDOs de 2ª ordem lineares.

Usaremos o **Classroom** como Ambiente Virtual de Aprendizagem (AVA), onde serão postadas as notas e realizadas as discussões e comunicações.


Para o módulo de **Cálculo Integral**, usaremos com livro texto a referência [@stewart1], e para o módulo de **EDO** usaremos [@Boyce]. **Essas duas referências estão disponíveis para empréstimo na Biblioteca do campus** -- [BRO](https://bibliotecas.uff.br/bro/). <span style="color:red">É altamente recomendado que vocês consultem este material, de preferência, o livro físico.</span>

As demais referência contidas na @sec-ref serão usadas como material auxiliar ao longo do curso.\


# Avaliação

A avaliação será feita mediante:

1. Exercícios propostos em aula, chamados de **Para Casa** :house: 
2. **Duas Provas Escritas**. 

A nota final será a média ponderada entre os **Para Casa** e as **Provas Escitas**, distribuídas da seguinte forma:
$$N=0.2\times PC+0.8\times P,$$
onde $PC$ é a média dos Para Casa e $P$ a média das Provas Escritas. Veja no cronograma, @sec-crono abaixo, as datas destas avaliações. 

## Sobre os Para Casa

- Deverá ser feito em grupos de 4 a 5 integrantes.
- Deverá ser manuscrito.
- Deverá ser entregue em folhas de **papel A4 ou almaço e grampeadas**.

## Sobre as Provas

- Serão **escritas e com consulta** a qualquer material impresso ou manuscrito (livros, notas de aula, caderno, apostilas e etc.).
- <span style="color:red"> Não será permitido o uso de dispositivos eletrônicos com acesso à internet (tablets, celulares e etc).</span> 
- Será permitido o uso de calculadora científica.



## Segunda Chamada

O Art. 98 do  [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) garante ao aluno  o direito a uma avaliação de **Segunda Chamada (VR)**, <span style="color:red">sem a necessidade de justificativa!</span> Portanto, aquele aluno que **não puder ou não quiser** fazer uma das provas, poderá faltar que seu direito à Segunda Chamada será garantido.


::: {.callout-warning}
## Importante

Como **não há a necessidade de justificar a falta nas avaliações** para ter o direito à Segunda Chamada garantido, alguns alunos usam este direito para fazer a Segunda Chamada quando não se sentem suficientemente preparados para alguma das avaliações. 

Por conta disso, o aluno que estiver em dúvida entre fazer a prova ou a Segunda chamada, poderá comparecer no dia da prova e tentar fazê-la. Caso não se sinta preparado, poderá desistir e ainda terá o direito a fazer a Segunda Chamada. Aqueles que permanecerem e entregarem definitivamente a prova não terão o direito à Segunda Chamada.
:::

## Verificação Suplementar

Em concordância com o [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) em seu Art. 99, a **Verificação Suplementar (VS)** é vetada aos discentes já aprovados e é **obrigatória** para aqueles que tenham obtido média parcial entre 4,0 e 5,9, sendo esses dois limites incluídos.



# Listas de Exercícios

**Integral**: Abaixo seguem os execícios da referência @stewart1 que devem ser feitos. Os exercícios marcado com o símbolo SAC no livro, devem ser feitos usando uma ferramenta computacional, como por exemplo o python.

§ 5.1: 11, 15.\
§ 5.2: 5, 33, 35, 37, 47, 49, 53.\
§ 5.3: 7, 9, 17, 19, 23, 27, 29, 35, 39, 53, 55.\
§ 5.4: 5, 9, 11, 17, 29, 31, 35, 37, 41, 61.\
§ 5.5: 7, 9, 19, 21, 23, 27, 35, 53, 57, 59, 63, 74, 76, 78, 81.\
§ 6.1: 1, 3, 5, 9, 13, 23, 24, 29, 39, 49, 51, 53.\
§ 7.1: 3, 5, 7, 9, 15, 17, 23, 25, 27, 33, 44, 47.\
§ 7.2: 3, 7, 17, 21, 25, 29, 31, 43, 45, 56, 57, 66, 70.\
§ 7.3: 5, 7, 11, 13, 17, 23, 25, 35, 41.\
§ 7.4: 7, 9, 11, 13, 15, 17, 63, 65, 67.\
Leia a seção 7.5 (Estratégias de Integração)\
§ 7.5: 1, 3, 5, 7, 13, 15, 17, 23, 25, 27, 33, 41, 45, 63.\
§ 6.2: 1, 3, 5,19, 21, 39, 45, 51, 67.\
§ 6.3: 5, 7, 9, 15, 19, 43, 46.\
§ Em construção

**EDO**: Abaixo seguem os execícios da referência @Boyce que devem ser feitos. A distribuição está dada por seção. Os exercícios marcado com o símbolo🖱️​ no livro, devem ser feitos usando uma ferramenta computacional, como por exemplo o python.

§ 1.1: 1, 5, 11, 13, 22, 23.\
§ 1.3: 1, 2, 5, 6, 8, 9, 11, 15.\
§ 2.2: 1, 6, 8, 10, 12 .\
§ 2.3: 12, 13, 16, 21.\
§ 2.1: 1, 4, 5, 6, 7, 9, 13, 15, 16, 17,18.\
§ 2.4: 1, 2, 5, 7, 11, 27, 28.\
§ 3.1: 1-4, 9-12, 20, 21, 22.\
§3.2: 1,2, 21, 22, 23, 25.\
§3.4: 7-10, 17-20, 25.\
§3.5: 1-4, 11-14, 15, 18.\
§3.6: 1-5, 8, 14, 17.\
§3.7: 5-7, 13, 14.\
§3.8: 6, 9, 11, 14, 17, 27.

# Referências {#sec-ref}


::: {#refs}
:::




# Cronograma Efetivado {#sec-crono}

**1.1 A integral e Técnicas de integração**

:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  23/09  --  Participação em Congresso -- Não houve aula </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  24/09  --  Participação em Congresso --  Não houve aula </span> \
01 . &nbsp; Seg  --  30/09  --  <span style="color:standard"> Apresentação. Método da Exaustão. Notação Sigma. Somas de Riemann. Integral Definida. Teorema Fundamental do Cálculo. </span> \
02 . &nbsp; Ter  --  01/10  --  <span style="color:standard"> Propriedades da Integral.  Integral indefinida. Integrais Elementares. Integral por Substituição. Integração por partes, exemplo 1. </span> \
03 . &nbsp; Seg  --  07/10  --  <span style="color:standard"> Integração por Partes. Integração por substituição Trigonométrica. Área do Círculo. Integração de funções racionais: frações parciais. </span> \
04 . &nbsp; Ter  --  08/10  --  <span style="color:standard">  Áreas entre curvas. Cálculo de volumes por fatiamento. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sáb  --  12/10  --  Nossa Senhora Aparecida </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  14/10  --  Semana Nacional de Ciência e Tecnologia </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  15/10  --  Semana Nacional de Ciência e Tecnologia </span> \
---

**1.2 Aplicações da Integral**

05 . &nbsp; Seg  --  21/10  --  <span style="color:standard"> Volume pelo método dos discos. Sólidos de Revolução ✊. Volume por cascas cilíndricas.   Comprimento de Curvas. O comprimento da circunferência</span> \
06 . &nbsp; Ter  --  22/10  --  <span style="color:standard"> Integrais Impróprias. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  28/10  --  Servidor Público </span> \
07 . &nbsp; Ter  --  29/10  --  <span style="color:standard"> Testes de convergência.   </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sáb  --  02/11  --  Finados </span> \
08 . &nbsp; Seg  --  04/11  --  <span style="color:standard"> Aula de Dúvidas e exercícios. Lemos a abertura do Guia do Mochileiro das Galáxias. </span> \
09 . &nbsp; Ter  --  05/11  --  <span style="color:standard"> não haverá aula -- participação em congresso. </span> \
10 . &nbsp; Seg  --  11/11  --  <span style="color:standard">  Aula de exercícios  </span> \
11 . &nbsp; Ter  --  12/11  --  <span style="color:standard"> Aula de Exercícios  </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  15/11  --  Proclamação da República </span> \
12 . &nbsp; Seg  --  18/11  --  <span style="color:standard"> Aula de Exercícios  </span> \
<span style="color:red"> 13 . &nbsp; Ter  --  19/11  --  1ª Prova </span> --
[gabarito](provas/2024-2-p1-c2-gabarito.pdf)\
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  20/11  --  Consciência Negra </span> \
---

**2.1 EDOs de 1ª ordem**

14 . &nbsp; Seg  --  25/11  --  <span style="color:standard"> Classificação e solução. Campos direcionais. Equações Separáveis 1ª ordem, EDO 1ª ordem linear. Crescimento populacional malthusiano e logístico. </span> \
15 . &nbsp; Ter  --  26/11  --  <span style="color:standard"> Queda livre com resistência do ar. Ilustração do modelo SIR.  </span> \
16 . &nbsp; Seg  --  02/12  --  <span style="color:standard"> Equações Exatas e fator integrante. </span> \
17 . &nbsp; Ter  --  03/12  --  <span style="color:standard"> Aula de Exercícios </span> \
18 . &nbsp; Seg  --  09/12  --  <span style="color:standard"> Teorema de Existência e Unicidade de Soluções para EDO de 1ª ordem lineares. Revisão de números complexos e fórmula de Euler. -- ([lista número complexos](lista-complexos.pdf))  </span> \
---

**2.2 EDOs de 2ª ordem lineares**

19 . &nbsp; Ter  --  10/12  --  <span style="color:standard">Continuação Números complexos. EDO’s 2ª ordem lineares. Teorema de Existência e Unicidade.  </span> \
20 . &nbsp; Seg  --  16/12  --  <span style="color:standard"> Soluções Fundamentais. Wronskiano. Oscilações mecânicas livres com amortecimento. </span> \
21 . &nbsp; Ter  --  17/12  --  <span style="color:standard"> Não houve aula.  </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  23/12  --  Recesso </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  24/12  --  Recesso </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  30/12  --  Recesso </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  31/12  --  Recesso </span> \
22 . &nbsp; Seg  --  06/01  --  <span style="color:standard"> EDO linear homogênea com coeficientes constantes. </span> \
23 . &nbsp; Ter  --  07/01  --  <span style="color:standard"> Método dos coeficientes a determinar e Método da variação dos Parâmetros. </span> \
24 . &nbsp; Seg  --  13/01  --  <span style="color:standard"> Aula de Exercícios. </span> \
25 . &nbsp; Ter  --  14/01  --  <span style="color:standard"> Aula de Exercícios. </span> \
26 . &nbsp; Seg  --  20/01  -- <span style="color:LightGray">  Aula de Dúvidas </span> \
---

**Provas Finais**


<span style="color:red"> 27 . &nbsp; Ter  --  21/01  --  2ª Prova  </span> --  [gabarito](provas/2024-2-p2-c2-gabarito.pdf)\
<span style="color:red"> 28 . &nbsp; Seg  --  27/01  --  2ª Chamada </span> \
 -- &nbsp; Ter  --  28/01  --  <span style="color:LightGray">  Não haverá aula  </span> \
 -- &nbsp; Seg  --  03/02  --  <span style="color:LightGray"> Não haverá aula  </span> \
<span style="color:red">29 . &nbsp; Ter  --  04/02  --   VS  </span> \
:end: &nbsp; Qui  --  06/02  --  Fim do Período. :raised_hands:
---


# Resultados
Inicialmente foram **46 inscritos**, entretanto ao final do curso ficamos com **X** estudantes.

## 1ª Prova {-}



```{python}
#| echo: false
#| output: asis

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt


p1 = np.array([5.3,5.2,6.8,5,6.3,2.9,8.1,5.8,5.6,8.8,8,8.1,2.8,6.6,4.9,7.3,4.4,5.6,4.6])
N=len(p1)

print('Compareceram à 1ª prova ','**'+str(N)+'**',' alunos, de um total de **46 inscritos**, isto é, ',round(N/46*100,2),' %')
print( )

# Plot the histogram.
plt.hist(p1, bins=10, density=False, alpha=0.6, color='b',edgecolor='black')

# Adicionar título e legendas
plt.title("Histograma das Notas da P1")
plt.xlabel('Notas')
plt.ylabel('Nº de alunos')


plt.show()

```

## 2ª Prova {-}

```{python}
#| echo: false
#| output: asis

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt


p1 = np.array([
1,10,0,0.5,8,9.5,7.2,6,10,2.5,1.5,10,10,9.3,8.8,7.5,7.3,4.5,5,0.5,0,1,])
N=len(p1)

print('Compareceram à 2ª prova ','**'+str(N)+'**',' alunos, de um total de **46 inscritos**, isto é, ',round(N/46*100,2),' %')
print( )

# Plot the histogram.
plt.hist(p1, bins=10, density=False, alpha=0.6, color='b',edgecolor='black')

# Adicionar título e legendas
plt.title("Histograma das Notas da P2")
plt.xlabel('Notas')
plt.ylabel('Nº de alunos')

plt.show()

```











# Cronograma Proposto Inicialmente

Este foi o programa proposto no início do perído, que será mantido aqui para fins de comparação com o cronograma que realmente foi efetivado acima.

**1.1 A integral e Técnicas de integração**

:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  23/09  --  Participação em Congresso -- Não houve aula </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  24/09  --  Participação em Congresso --  Não houve aula </span> \
01 . &nbsp; Seg  --  30/09  --  <span style="color:Black"> Apresentação. Método da Exaustão. Notação Sigma. Somas de Riemann. Integral Definida. Teorema Fundamental do Cálculo. </span> \
02 . &nbsp; Ter  --  01/10  --  <span style="color:Black"> Propriedades da Integral.  Integral indefinida. Integrais Elementares. Integral por Substituição </span> \
03 . &nbsp; Seg  --  07/10  --  <span style="color:Black"> Integração por Partes. Integração por substituição Trigonométrica </span> \
04 . &nbsp; Ter  --  08/10  --  <span style="color:Black"> Integração de funções racionais: frações parciais. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sáb  --  12/10  --  Nossa Senhora Aparecida </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  14/10  --  Semana Nacional de Ciência e Tecnologia </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  15/10  --  Semana Nacional de Ciência e Tecnologia </span> \
---

**1.2 Aplicações da Integral**

05 . &nbsp; Seg  --  21/10  --  <span style="color:Black"> Área do Círculo. Áreas entre curvas. </span> \
06 . &nbsp; Ter  --  22/10  --  <span style="color:Black"> Cálculo de volumes por fatiamento. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  28/10  --  Servidor Público </span> \
07 . &nbsp; Ter  --  29/10  --  <span style="color:Black"> Volume pelo método dos discos. Sólidos de Revolução ✊. Volume por cascas cilíndricas. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sáb  --  02/11  --  Finados </span> \
08 . &nbsp; Seg  --  04/11  --  <span style="color:Black"> Comprimento de Curvas. O comprimento da circunferência </span> \
09 . &nbsp; Ter  --  05/11  --  <span style="color:Black"> Integrais Impróprias: Limites Infinitos. </span> \
10 . &nbsp; Seg  --  11/11  --  <span style="color:Black"> Integrais Impróprias: Integrandos Descontínuos.  </span> \
11 . &nbsp; Ter  --  12/11  --  <span style="color:Black"> Teste de comparação. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  15/11  --  Proclamação da República </span> \
12 . &nbsp; Seg  --  18/11  --  <span style="color:Black"> Aula de Exercícios 1 </span> \
<span style="color:red"> 13 . &nbsp; Ter  --  19/11  --  1ª Prova </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  20/11  --  Consciência Negra </span> \
---

**2.1 EDOs de 1ª ordem**

14 . &nbsp; Seg  --  25/11  --  <span style="color:Black"> EDOs: modelos (populacionais, massa-mola, pêndulo, queda livre com resistência do ar) </span> \
15 . &nbsp; Ter  --  26/11  --  <span style="color:Black"> Classificação e solução. Campos direcionais. Equações Separáveis 1ª ordem, EDO 1ª ordem linear </span> \
16 . &nbsp; Seg  --  02/12  --  <span style="color:Black"> Equações Exatas e fator integrante. </span> \
17 . &nbsp; Ter  --  03/12  --  <span style="color:Black"> Teorema de Existência e Unicidade de Soluções para EDO de 1ª ordem lineares </span> \
18 . &nbsp; Seg  --  09/12  --  <span style="color:Black"> Aula de Exercícios 2 </span> \
---

**2.2 EDOs de 2ª ordem lineares**

19 . &nbsp; Ter  --  10/12  --  <span style="color:Black"> EDO’s 2ª ordem lineares. Teorema de Existência e Unicidade. Soluções Fundamentais. Wronskiano </span> \
20 . &nbsp; Seg  --  16/12  --  <span style="color:Black"> Oscilações mecânicas livres com amortecimento. EDO 2ª ord. linear homogênea com coef. constantes - caso raízes distintas </span> \
21 . &nbsp; Ter  --  17/12  --  <span style="color:Black"> EDO linear homogênea com coeficientes constantes - caso raízes reais iguais. Revisão de números complexos e fórmula de Euler </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  23/12  --  Recesso </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  24/12  --  Recesso </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  30/12  --  Recesso </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  31/12  --  Recesso </span> \
22 . &nbsp; Seg  --  06/01  --  <span style="color:Black"> EDO linear homogênea com coeficientes constantes -  Caso raízes complexas.Método dos coeficientes a determinar </span> \
23 . &nbsp; Ter  --  07/01  --  <span style="color:Black"> Método da variação dos Parâmetros </span> \
24 . &nbsp; Seg  --  13/01  --  <span style="color:Black"> Método da variação dos Parâmetros </span> \
25 . &nbsp; Ter  --  14/01  --  <span style="color:Black"> Aula de Exercícios 3 </span> \
---

**Provas Finais**

<span style="color:red"> 26 . &nbsp; Seg  --  20/01  --  2ª Prova </span> \
<span style="color:red"> 27 . &nbsp; Ter  --  21/01  --  2ª Chamada </span> \
<span style="color:red"> 28 . &nbsp; Seg  --  27/01  --  VS </span> \
29 . &nbsp; Ter  --  28/01  --   --  \
30 . &nbsp; Seg  --  03/02  --   --  \
31 . &nbsp; Ter  --  04/02  --   --  \
:end: &nbsp; Qui  --  06/02  --  Fim do Período. :raised_hands:
