---
title: Minicurso EDOs em Espaços de Banach -- 2025-Verão
number-sections: false

format:
  html:
    toc: true
from: markdown+emoji
---


\begin{equation*}
\begin{cases}
x'(t)={\color{red}A}x+{\color{black}f},& t\in [0,+\infty)\\
x(0)=x_0
\end{cases}
\end{equation*}
\begin{equation*}
x(t)=e^{t\color{red}A}x_0+\int_0^t e^{(t-s){\color{red}A}}f(s)ds
\end{equation*}

# Informações Básicas

- **Professores:** Luiz Viana (UFF -- Campus Niterói ) e Reginaldo Demarque (UFF -- Campus Rio das Ostras)

- **Período:** 12/02/2025 a 21/02/2025 na Escola de Verão da [PGMAT-UFF](https://pgmat-uff.com.br/verao-2025/)

- **Nível:** Graduação e Mestrado.

- **Público alvo:** O presente minicurso tem como público alvo alunos dos cursos de graduação e mestrado, a distância ou presencial, em Matemática.
    

- **Horário e sala:** \

    - 11h às 13h dos dias 12, 13, 14, 19, 20 e 21 de fevereito de 2025.  
    - Auditório 407 do Bloco H do PGMAT-UFF.

- **Material a ser utilizado**
    - [Slides](curso-semigrupo.pdf)  
    - [Notas de semigrupos](https://reginaldodr.github.io/notas-semigrupos-git/notas-semigrupo.pdf)
    
-  **Programação:**  Neste minicurso, temos o objetivo de introduzir a Teoria dos Semigrupos Lineares, que consiste no estudo das equações diferenciais ordinárias, com valores em espaços de Banach, associadas a operadores lineares limitados ou ilimitados. Brevemente, vale ressaltar que tal estudo foi iniciado a partir da segunda metade do século XX, destacando-se a obtenção do importante teorema de Hille-Yosida em 1948. Nas décadas de 70 e 80, através de muitas contribuições vindas de diferentes escolas de Matemática, o tema se consolidou nos moldes que o conhecemos hoje, o que pode ser constatado com os trabalhos E. B. Davies, J. A. Goldstein e A. Pazy, entre outros. Nas exposições pretendidas, abordaremos resultados abstratos básicos da teoria e, ao final, apresentaremos algumas aplicações relacionadas às equações diferenciais parciais. 

- **Pré-requistos:** Análise Real e Equações Diferenciais Ordinárias.

# Cronograma {#sec-crono}

O presente minicurso corresponde às seções 1.1 a 1.3 da referência (Pazy, 2012).

01 . &nbsp; Qua  --  12/02  --  <span style="color:standard"> Apresentação do minicurso. Espaços de Banach $X$. Operadores Lineares Limitados. Exponencial de Operadores em $\mathcal{L}(X)$.</span> \
\
02 . &nbsp; Qui  --  13/02  --  <span style="color:standard">  Definição de Semigrupos de classe $C^0$. Exemplos. Teorema de Banach-Steinhauss. Limitação  e continuidade de semigrupos. </span> \
\
03 . &nbsp; Sex  --  14/02  --  <span style="color:standard">  Gerador Infinitesimal de um Semigrupo. Existência e Unicidade do PVI para geradores infinitesimais.  </span> \
\
04 . &nbsp; Qua  --  19/02  --  <span style="color:standard"> Espectro de um semigrupo. Resolvente de um operador. Teorema do Gráfico Fechado. O Teorema de Hille-Yosida para contrações: ($\Rightarrow$)   </span> \
\
05 . &nbsp; Qui  --  20/02  --  <span style="color:standard"> Semigrupos das Contrações. Aproximação de Yosida. O Teorema de Hille-Yosida para contrações: ($\Leftarrow$). </span> \
\
06 . &nbsp; Sex  --  21/02  --  <span style="color:standard">  Aplicações em EDPs. Perspectivas de Pesquisa. </span> \


# Referências {#sec-ref}

-  Brezis, Haim. Functional analysis, Sobolev spaces and partial differential equations. Springer, New York-London, 2011.

- Engel, Klaus-Jochen, and Rainer Nagel. One-parameter semigroups for linear evolution equations. Graduate Text in Mathematics 194, Springer-Verlag New York, 2000.

- Engel, Klaus-Jochen, and Rainer Nagel. A short course on operator semigroups. Springer Science & Business Media, 2006.

- Evans, Lawrence C. Partial differential equations, volume 19. American Mathematical Society, Providence, Rhode Island, 2010.


-  Gomes, Alvercio Moreira. Semigrupos de Operadores Lineares e Aplicações às Equações de Evolução, volume 2ª edição. Editora UFRJ, Rio de Janeiro, Rio de Janeiro, 2005.

-  Kesavan, S. Topics in Functional Analysis and Applications, volume 52. New Age International Ltd, New Delhi, 2015.


- Pazy, Amnon. Semigroups of linear operators and applications to partial differential equations. Vol. 44. Springer Science & Business Media, 2012.



