---
title: CÁLCULO III RCN00021 -- 2023-2
number-sections: true
bibliography: ../biblio.bib
csl:  aims-mathematics.csl

nocite: |
  @thomas2, @diomara, @tromba,
  
format:
  html:
    toc: true
from: markdown+emoji
---



# Informações Básicas

-   Horários e Salas

    -   **Horário e sala:** 4ª e 6ª das 14h às 16h --  **sala 04 -- IHS (prédio alugado)**\
    confira no [Quadro de Alocação de salas do IHS](http://200.159.243.2:10032/home/index_simples)

    -   **Atendimento**: sala 104 -- IHS (prédio alugado)
    
- [Material a ser utilizado](calculoIII.qmd)

-   Ementa: Busque por RCN00021 em [quadro de horários](https://app.uff.br/graduacao/quadrodehorarios/)

FUNÇÕES VETORIAIS DE UMA VARIÁVEL. FUNÇÕES REAIS DE VÁRIAS VARIÁVEIS. CONTINUIDADE.
DERIVADAS PARCIAIS E DIFERENCIABILIDADE. FÓRMULA DE TAYLOR.




# Apresentação do Curso

Este curso é constituído de dois módulos: **Funções Vetoriais** e **Funções de Várias Variáveis**.

Usaremos o **Classroom** como Ambiente Virtual de Aprendizagem (AVA), onde serão postadas as notas e realizadas as discussões e comunicações.


O **livro texto** será referência [@stewart2], que **está disponíveis para empréstimo na Biblioteca do campus** -- [BRO](https://bibliotecas.uff.br/bro/). <span style="color:red"> É altamente recomendado que vocês consultem este material, de preferência o livro físico.</span>

As demais referência contidas na @sec-ref formam uma lista complementar/auxiliar do curso, foram usados principalmente na elaboração das notas de aulas e exemplos.

# Avaliação

A avaliação será constituída de **2 Provas** presenciais realizadas ao fim de cada módulo, de acordo com o cronograma em @sec-crono.

Cada prova terá o **valor de 10 pontos.** A nota final do curso será a média aritmética das provas.

As duas provas serão **escritas e com consulta** a qualquer material impresso ou manuscrito (livros, notas de aula, caderno, apostilas e etc.). <span style="color:red"> Não será permitido o uso de dispositivos eletrônicos com acesso à internet (tablets, celulares e etc).</span> Será permitido o uso de calculadora científica.

## Segunda Chamada

O Art. 98 do  [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) garante ao aluno  o direito a uma avaliação de **Segunda Chamada (VR)**, <span style="color:red">sem a necessidade de justificativa!</span> Portanto, aquele aluno que **não puder ou não quiser** fazer uma das provas, poderá faltar que seu direito à Segunda Chamada será garantido.

A Segunda Chamada de todas as avaliações será feita no mesmo dia (veja data na @sec-crono). Será elaborada uma prova de Segunda Chamada para cada avaliação regular do curso, no mesmo nível destas avaliações. 

Contudo, cabe ressaltar que, de acordo com o mesmo artigo, a Segunda Chamada **substituirá uma, e somente uma,** das avaliações que tenha faltado. Portanto, se o aluno faltar a mais de uma avaliação, no dia da Segunda Chamada poderá escolher qual fará, mas só poderá fazer uma das avaliações.


::: {.callout-warning}
## Importante

Como **não há a necessidade de justificar a falta nas avaliações** para ter o direito à Segunda Chamada garantido, alguns alunos usam este direito para fazer a Segunda Chamada quando não se sentem suficientemente preparados para alguma das avaliações. 

Por conta disso, os primeiros 30 minutos de cada  avaliação serão reservados para o aluno decidir melhor se quer fazer a prova ou deixará para fazer a Segunda Chamada. Isto é, o aluno que estiver em dúvida entre fazer a prova ou a Segunda chamada, poderá comparecer no dia da prova e tentar fazê-la. Caso não se sinta preparado, dentro dos  primeiros 30 minutos, poderá desistir e ainda terá o direito a fazer a Segunda Chamada. Aqueles que permanecerem após os 30 minutos não terão mais o direito à Segunda Chamada.
:::

## Verificação Suplementar

Em concordância com o [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) em seu Art. 99, a **Verificação Suplementar (VS)** é vetada aos discentes já aprovados e é **obrigatória** para aqueles que tenham obtido média parcial entre 4,0 e 5,9, sendo esses dois limites incluídos.

# Listas de Exercícios

Abaixo seguem os execícios da referência [@stewart2] que devem ser feitos. A distribuição está dada por seção.

§ 12.5: 3, 5, 7, 9, 23, 26, 31, 43.\
§ 12.6: 3, 5, 13, 15, 21, 23, 25, 27, 29, 31.\
§ 10.3: 1, 3, 7, 9, 11, 15, 17, 19, 21, 23, 25, 29, 31, 33, 35, 37, 39, 41.\
§ 13.1: 7, 9, 11, 19-24, 27, 37, 39.\
§ 13.2: 3, 5, 17, 19, 25.\
§13.3: 1, 3, 11, 13, 15, 17, 21, 23, 27, 43, 59.\
§ 13.4: 3, 5, 11, 13, 19, 33, 35, 37, 41.\
§ 14.1: 11, 13, 15, 17, 19, 23, 25, 27, 30, 39, 41, 45, 49, 61, 63.\
§ 14.2: 5, 7, 9, 11, 13, 15, 29, 31, 35, 39, 41.\
§ 14.3: 15, 17, 21, 23, 25, 29, 31, 39, 41, 51, 53, 61, 63, 65.\
§ 14.4: 1, 3, 5, 11, 13, 21, 25, 27, 33, 35, 37.\
§ 14.5: 1, 3, 5, 7, 15, 17, 19, 21, 23, 35, 43.\
§ 14.6: 5, 7, 9, 11, 15, 17, 21, 23, 25, 29, 31, 34, 39, 41, 53.\
§ 14.7: 5, 7, 13, 15, 31, 33, 34, 35, 39, 41, 43, 47, 53.\
§ 14.8: 3, 5, 9, 15, 17, 19, 41, 43.

Exercícios do **Stewart Vol. 2, 7ª Edição.**

§ 14.7: 5, 7, 11, 13, 15, 31, 33, 34, 35, 39, 41, 43, 47, 53.\
§ 14.8: 3, 5, 9, 15, 17, 19, ,21, 45.

# Referências {#sec-ref}


::: {#refs}
:::

# Cronograma {#sec-crono}

A seguir temos a proposta de cronograma para este curso. Esta proposta pode sofrer pequenas alterações ao longo do curso que, caso ocorram, serão comunicadas aos alunos. **Cabe ressaltar que o semestre se encerra no dia 20/12, neste caso, é aconselhado que fiquem disponíveis até esta data.**

## Cronograma Efetivado

01 . &nbsp; Qua  --  30/08  -- Apresentação. Funções Vetoriais. Limite e continuidade. Curvas parametrizadas no Plano. **Próxima Aula:** resolver Para :house: 1 e 2. \
02 . &nbsp; Sex  --  01/09  -- Resolução dos Para :house: . Revisão de alguns conceitos de GA. Parametrização de Círculos como interseção de duas superfícies. Definição de Coordenadas Polares.  \
03 . &nbsp; Qua  --  06/09  --  Cardioide. Parametrização com coordenadas polares.  Curvas parametrizadas no Espaço. Hélices. Derivadas e regras de derivação de funções vetoriais. **Próxima aula:** Resolver Para :house: 3 e 4. \
<span style="color:orange"> XX . &nbsp; Qui  --  07/09  --  Independência </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  08/09  --  Facultativo </span> \
04 . &nbsp; Qua  --  13/09  -- Resolução dos Para :house: 3 e 4. Comprimento de arco. Parametrização pelo comprimento de arco. **Próxima aula:** Resolver Para :house: 5. \
05 . &nbsp; Sex  --  15/09  -- Resolução do Para :house: 5.  Vetor Tangente e Curvatura. Vetores Normal e Binormal. Movimento, velocidade e aceleração. Componentes Normal e Tangencial da Aceleração. \
06 . &nbsp; Qua  --  20/09  -- Fórmula da curvatura. Fizemos o Para :house: 6 em aula. \
07 . &nbsp; Sex  --  22/09  --  Aula de Dúvidas. \
<span style="color:red"> 08 . &nbsp; Qua  --  27/09  --  1ª Prova </span> -- [gabarito](provas/2023-2-p1-M1-c3-gabarito.pdf) \
09 . &nbsp; Sex  --  29/09  --  Definição de Funções de Várias Variáveis. Gráficos de funções de 2 variáveis. Curvas de Nível. Superfícies de nível. **Próxima aula:** Resolver Para :house: 7 \
10 . &nbsp; Qua  --  04/10  -- Resolução do Para :house: 7.   Limites e continuidade. **Próxima aula:** Resolver Para :house: 8. \
XX . &nbsp; Qui  --  05/10  --  Vista da P1 - das 14h às 18h - sala 104  \
11 . &nbsp; Sex  --  06/10  -- Resolução do Para :house: 8.  Derivadas Parciais. Derivadas de ordem superior. EPDs: Funções Harmônicas e Equação da Onda. **Próxima aula:** Resolver Para :house: 9.\
XX . &nbsp; Ter  --  10/10  --   Vista da P1 - das 14h às 18h - sala 104  \
12 . &nbsp; Qua  --  11/10  --  Resolução do Para :house: 9 e 10. Plano Tangente. Aproximação Linear e Diferenciabilidade em $\mathbb{R}^2$. Exemplo 1. \
<span style="color:orange"> XX . &nbsp; Qui  --  12/10  --  Nossa Senhora Aparecida </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  13/10  --  Facultativo </span> \
<span style="color:orange"> XX . &nbsp; Qua  --  18/10  --  Semana Nacional de Ciência e Tecnologia </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  20/10  --  Semana Nacional de Ciência e Tecnologia </span> \
13 . &nbsp; Qua  --  25/10  -- Diferenciabilidade exemplo 2. Função de classe $C^1$ e Difrenciais em $\mathbb{R}^2$. \
14 . &nbsp; Sex  --  27/10  --  Diferenciabilidade. Diferenciais em $\mathbb{R}^3$. Regra da Cadeia. Resolver Para :house: 11 e 12. \
<span style="color:orange"> XX . &nbsp; Sáb  --  28/10  --  Servidor Público </span> \
15 . &nbsp; Qua  --  01/11  --  Resolução do Para :house: 11. Vetor Gradiente. Derivadas direcionais. \
<span style="color:orange"> XX . &nbsp; Qui  --  02/11  --  Finados </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  03/11  --  Facultativo </span> \
16 . &nbsp; Qua  --  08/11  --  Não pude dar aulas, estava com sintomas de covid. \
17 . &nbsp; Sex  --  10/11  --  Não pude dar aula -- tive consulta médica no dia que não podia ser adiada.  \
<span style="color:orange"> XX . &nbsp; Qua  --  15/11  --  Proclamação da República </span> \
18 . &nbsp; Sex  --  17/11  --  Propriedades do vetor Gradiente. Derivação Implícita e Teorema da Função Implícita no $\mathbb{R}^2$.  \
<span style="color:orange"> XX . &nbsp; Seg  --  20/11  --  Consciência Negra </span> \
19 . &nbsp; Qua  --  22/11  --   Derivação Implícita e Teorema da Função Implícita no $\mathbb{R}^3$.  Valores Máximo e Mínimo. Pontos críticos. Teste da Derivada Segunda. \
20 . &nbsp; Sex  --  24/11  -- Topologia do $\mathbb{R}^2$.  Máximos e Mínimos absolutos. Teorema de Weiestrass. Multiplicadores de Lagrange em $\mathbb{R}^2$.  \
21 . &nbsp; Qua  --  29/11  --  Aula de Exercícios \
<span style="color:red"> 22 . &nbsp; Sex  --  01/12  --  2ª Prova </span> -- [gabarito](provas/2023-2-p2-turmaM1-calculo3-gabarito.pdf) \
<span style="color:red"> 23 . &nbsp; Qua  --  06/12  --  2ª Chamada </span> \
<span style="color:red"> 24 . &nbsp; Sex  --  08/12  --  VS </span> \
25 . &nbsp; Qua  --  13/12  --  <span style="color:LightGray">  --  </span> \
26 . &nbsp; Sex  --  15/12  --  <span style="color:LightGray">  --  </span> \
27 . &nbsp; Qua  --  20/12  --  <span style="color:LightGray">  --  </span> \

---

## Cronograma Proposto Incialmente

Este foi o programa proposto no início do perído, que será mantido aqui para fins de comparação com o cronograma que realmente foi efetivado acima.

01 . &nbsp; Qua  --  30/08  --  Apresentação. Funções Vetoriais. Limite e continuidade \
02 . &nbsp; Sex  --  01/09  --  Curvas parametrizadas no Plano, Coordenadas polares \
03 . &nbsp; Qua  --  06/09  --  Curvas parametrizadas no Espaço. Derivadas e regras de derivação de funções vetoriais \
<span style="color:orange"> XX . &nbsp; Qui  --  07/09  --  Independência </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  08/09  --  Facultativo </span> \
04 . &nbsp; Qua  --  13/09  --  Comprimento de arco. Parametrização pelo comprimento de arco \
05 . &nbsp; Sex  --  15/09  --  Curvatura, Vetores Normal e Binormal. \
06 . &nbsp; Qua  --  20/09  --  Movimento, velocidade e aceleração. Componentes Normal e Tangencial da Aceleração \
07 . &nbsp; Sex  --  22/09  --  Aula de Dúvidas \
<span style="color:red"> 08 . &nbsp; Qua  --  27/09  --  1ª Prova </span> \
09 . &nbsp; Sex  --  29/09  --  Definição de Funções de Várias Variáveis. Gráficos de funções de 2 variáveis \
10 . &nbsp; Qua  --  04/10  --  Curvas de Nível. Superfícies de nível. Limites e continuidade \
11 . &nbsp; Sex  --  06/10  --  Superfícies de nível. Limites e continuidade \
12 . &nbsp; Qua  --  11/10  --  Derivadas Parciais. Derivadas de ordem superior \
<span style="color:orange"> XX . &nbsp; Qui  --  12/10  --  Nossa Senhora Aparecida </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  13/10  --  Facultativo </span> \
<span style="color:orange"> XX . &nbsp; Qua  --  18/10  --  Semana Nacional de Ciência e Tecnologia </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  20/10  --  Semana Nacional de Ciência e Tecnologia </span> \
13 . &nbsp; Qua  --  25/10  --  Equações Diferenciais Parciais. Plano tangente. Aproximação linear  \
14 . &nbsp; Sex  --  27/10  --  Diferenciabilidade. Diferenciais no plano e no espaço \
<span style="color:orange"> XX . &nbsp; Sáb  --  28/10  --  Servidor Público </span> \
15 . &nbsp; Qua  --  01/11  --  Regra da cadeia. Vetor Gradiente \
<span style="color:orange"> XX . &nbsp; Qui  --  02/11  --  Finados </span> \
<span style="color:orange"> XX . &nbsp; Sex  --  03/11  --  Facultativo </span> \
16 . &nbsp; Qua  --  08/11  --  Derivadas direcionais. Propriedades do vetor Gradiente \
17 . &nbsp; Sex  --  10/11  --  Derivação Implícita e Teorema da Função Implícita \
<span style="color:orange"> XX . &nbsp; Qua  --  15/11  --  Proclamação da República </span> \
18 . &nbsp; Sex  --  17/11  --  Valores Máximo e Mínimo. Pontos críticos. Teste da Derivada Segunda. Topologia do $\mathbb{R}^2$ \
<span style="color:orange"> XX . &nbsp; Seg  --  20/11  --  Consciência Negra </span> \
19 . &nbsp; Qua  --  22/11  --  Máximos e Mínimos absolutos. Teorema de Weiestrass. \
20 . &nbsp; Sex  --  24/11  --  Multiplicadores de Lagrange em $\mathbb{R}^2$. Multiplicadores de Lagrange em $\mathbb{R}^3$ \
21 . &nbsp; Qua  --  29/11  --  Multiplicadores de Lagrange com duas restrições \
<span style="color:red"> 22 . &nbsp; Sex  --  01/12  --  2ª Prova </span> \
<span style="color:red"> 23 . &nbsp; Qua  --  06/12  --  2ª Chamada </span> \
<span style="color:red"> 24 . &nbsp; Sex  --  08/12  --  VS </span> \
25 . &nbsp; Qua  --  13/12  --   --  \
26 . &nbsp; Sex  --  15/12  --   --  \
27 . &nbsp; Qua  --  20/12  --   -- 


