---
title: CÁLCULO III - A  RCN00067 -- 2025-1
number-sections: true
bibliography: ../biblio.bib
csl:  ../aims-mathematics.csl

nocite: |
  @thomas2, @diomara, @tromba,
  
format:
  html:
    toc: true
from: markdown+emoji
---



# Informações Básicas

- **Início e Fim do Período:** 24/03/2025 a 26/07/2025.

-  **Horário e sala:**\
[Quadro de Alocação de salas do IHS](http://159.112.185.66/home/index_simples) -- [acesso por celular](http://159.112.185.66/home_externo/index)  \

| Dia | Horário | Sala |
|----|----|----|
|Segunda |14h - 16h| Sala 04 (IHS Prédio Alugado)|
|Terça   |16h - 18h| Sala 06 (IHS Prédio Alugado)|
: {.striped .table-sm}



-  **Atendimento**: sala 104 -- IHS (prédio alugado)
    
- **Material a ser utilizado**

  - [slides](https://reginaldodr.github.io/slides/calculo3/calculo3.pdf)
  
  - [nota de aula](https://mega.nz/folder/3YdHDbxb#jm2ZKvf-lmg2zeloMK_z6Q)
  
  - [Lista de Exercícios Stewart](../lista-stewart6aEd-calculo3.pdf)

  - [VAs Antigas](../provas/)
  
  - [Exposição de Parboloides Hiperbóicos](/posts/exposicao-calculoIII-A-2015-1/exposicao.qmd)

-  **Ementa:** Busque por RCN00075 em [quadro de horários](https://app.uff.br/graduacao/quadrodehorarios/):\
EQUAÇÕES PARAMÉTRICAS. FUNÇÕES VETORIAIS. SUPERFÍCIES QUÁDRICAS E CILÍNDRICAS. FUNÇÕES DE VÁRIAS VARIÁVEIS, LIMITE, CONTINUIDADE, DERIVADAS DIRECIONAIS, OTIMIZAÇÃO E MULTIPLICADORES DE LAGRANGE.



# Apresentação do Curso

Este curso é constituído de dois módulos: **Funções Vetoriais e Superfícies** e **Funções de Várias Variáveis**.

O **livro texto** será referência [@stewart2], que **está disponíveis para empréstimo na Biblioteca do campus** -- [BRO](https://bibliotecas.uff.br/bro/). <span style="color:red"> É altamente recomendado que vocês consultem este material, de preferência o livro físico.</span>

As demais referência contidas na @sec-ref formam uma lista complementar/auxiliar do curso, foram usados principalmente na elaboração das notas de aulas e exemplos.

# Avaliação

A avaliação será feita mediante **2 Verificações de Aprendizagem (VA) Escritas**. A nota final (NF) será a média aritmética  entre elas.

## Objetivos {-}
As VAs tem como objetivos avaliar se o aluno:

- É capaz de interpretar as questões corretamente e formular soluções para os problemas propostos.
- É capaz de produzir soluções, em formato de texto, compreensíveis,  com nível de detalhamento e rigor adequados para que outros profissionais familiarizados com os conceitos possam entendê-las.
- Aprendeu os conceitos e técnicas ensinados em sala de aula. 
- Sabe determinar quando a solução proposta resolve de fato o problema. 
- Consegue desenvolver uma argumentação lógica-dedutiva para chegar-se à resposta final.


## Critério de correção das VAs {-}
Com base nos objetivos apresentados acima, os critério de correção serão: 

   1. Interpretação correta das questões.
   2. As soluções devem ser escrita com clareza, organização, rigor e detalhamento.
   3. Soluções desenvolvidas fora do conteúdo ensinado, mesmo que corretas, não serão consideradas.
   4. Questão com várias soluções será anulada.
   5. Resposta correta com solução errada será anulada.

Além disso, durante às VAs, serão adotadas as seguinte medidas: 

- Proibido compartilhar material.
- Só é permitida a saída após entrega definitiva da VA, ou seja, não é permitido ir ao banheiro ou beber água. A VA tem duração de no máximo 2 horas.
- É permitida a **consulta a material** (livros, notas de aula, caderno, apostilas e etc.)  e uso de dispositivo computacional, como calculadora científica, ambos **sem acesso a internet**.
- Fraude detectada, mesmo depois, zera a nota.

## Segunda Chamada {-}

O Art. 98 do  [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) garante ao aluno  o direito a uma avaliação de **Segunda Chamada (VR)**, <span style="color:red">**sem a necessidade de justificativa!**</span> Portanto, aquele aluno que **não puder ou não quiser** fazer uma das VAs, poderá faltar que seu direito à Segunda Chamada será garantido.

O conteúdo da **Segunda Chamada** será <span style="color:red">toda a matéria do semestre.</span>


::: {.callout-warning}
## Importante

Como **não há a necessidade de justificar a falta nas avaliações** para ter o direito à Segunda Chamada garantido, alguns alunos usam este direito para fazer a Segunda Chamada quando não se sentem suficientemente preparados para alguma das avaliações. 

Por conta disso, o aluno que estiver em dúvida entre fazer a VA ou a Segunda chamada, poderá comparecer no dia da VA e tentar fazê-la. Caso não se sinta preparado, poderá desistir e ainda terá o direito a fazer a Segunda Chamada. Aqueles que permanecerem e entregarem definitivamente a VA não terão o direito à Segunda Chamada.
:::

## Verificação Suplementar {-}

Em concordância com o [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) em seu Art. 99, a **Verificação Suplementar (VS)** é vetada aos discentes já aprovados e é **obrigatória** para aqueles que tenham obtido média parcial entre 4.0 e 5.9, sendo esses dois limites incluídos.

# Listas de Exercícios

Abaixo seguem os execícios da referência [@stewart2] que devem ser feitos. A distribuição está dada por seção. 

Veja a lista [aqui](../lista-stewart6aEd-calculo3.pdf)

O símbolo :pencil2: significa quais exercícios já podem ser feitos com o contéudo dado até o momento, enquanto o símbolo :lock: se refere àqueles que ainda não. A medida que o conteúdo em sala for avançando, novos exercícios serão desbloqueados.

- **Parametrização, coordenadas polares, superfícies e funções vetoriais**\

:pencil2: **§ 12.5 (Retas e Planos):** 3, 5, 7, 9, 23, 26, 31, 43, 45.\
:pencil2: **§ 12.6 (Cilindros e Quádricas):** 3, 5, 13, 15, 21-28, 29, 31, 33.\
:pencil2: **§ 10.3 (Coordenadas Polares):** 1, 3, 7, 9, 11, 15, 17, 19, 21, 23, 25, 29, 31, 33, 35, 37, 39, 41, 56.\
:pencil2: **§ 13.1 (Funções Vetoriais):** 7, 9, 11, 19-24, 27, 37, 38, 39.\
:pencil2: **§ 13.2 (Derivadas):** 3, 5, 17, 19, 21, 23, 25, 27 e 29.\
:pencil2: **§13.3 (Comprimento de arco e Curvatura):** 1, 3, 5, 11, 13, 15, 17(b), 19(b), 21, 23.\
:pencil2: **§ 13.4 (Velociade e Aceleração):** 3, 5, 11, 13, 19, 31,32, 41.\
---

- **Funções de Várias Variáveis**\

:pencil2: **§ 14.1 (Funções):** 11, 13, 15, 17, 19, 23, 25, 27, 30, 39, 41, 45, 49, 61, 63.\
:pencil2: **§ 14.2 (Limite e Continuidade):** 5, 7, 9, 11, 13, 15, 29, 31, 35, 39, 41.\
:pencil2: **§ 14.3 (Derivadas Parciais):** 15, 17, 21, 23, 25, 29, 31, 39, 41, 51, 53, 61, 63, 65.\
:pencil2: **§ 14.4 (Aproximação Linear):** 1, 3, 5, 11, 13, 21, 25, 27, 33, 35, 37.\
:pencil2: **§ 14.5 (Regra da Cadeia):** 1, 3, 5, 7, 15, 17, 19, 21, 23, 35, 43.\
:pencil2: **§ 14.6 (Vetor Gradiente):** 5, 7, 9, 11, 15, 17, 21, 23, 25, 29, 31, 34, 39, 41, 53.\
:pencil2: **§ 14.7 (Máximos e Mínimos):** 5, 7, 13, 15, 31, 33, 34, 35, 39, 41, 43, 47, 53.\
:pencil2: **§ 14.8 (Multiplicadores de Lagrange):** 3, 5, 9, 15, 17, 19, 41, 43.

Exercícios do **Stewart Vol. 2, 7ª Edição.**

:pencil2: § 14.7: 5, 7, 11, 13, 15, 31, 33, 34, 35, 39, 41, 43, 47, 53.\
:pencil2: § 14.8: 3, 5, 9, 15, 17, 19, ,21, 45.

# Referências {#sec-ref}


::: {#refs}
:::

# Cronograma Efetivado {#sec-crono}
A seguir temos a proposta de cronograma para este curso. Esta proposta pode sofrer pequenas alterações ao longo do curso que, caso ocorram, serão comunicadas aos alunos. **Cabe ressaltar que o semestre se encerra no dia  <span style="color:red"> 26/07 </span>,      neste caso, é aconselhado que fiquem disponíveis até esta data.**

**1. Funções vetoriais e Superfícies**

01 . &nbsp; Seg  --  24/03  --  <span style="color:standard"> Apresentação do estudantes. Apresentação do curso. Motivação: problemas de otimização. </span> \
02 . &nbsp; Ter  --  25/03  --  <span style="color:standard"> Revisão de equação paramétrica da reta e equação cartesiana do plano em $\mathbb{R}^3$. Coordenadas Polares. </span> \
03 . &nbsp; Seg  --  31/03  --  <span style="color:standard"> Superfícies  Cilíndricas. Superfícies Quádricas. </span> \
04 . &nbsp; Ter  --  01/04  --  <span style="color:standard"> Aula de Exercícios: Esboçando superfícies Quádricas. Forma resolvidos os exercícios do Stewart: - 12.6 (34, 50); 13.1 (12, 14, 28, 42); 13.2( 24, 26); 10.3 (10, 16, 30, 38) </span> \
05 . &nbsp; Seg  --  07/04  --  <span style="color:standard"> Funções Vetoriais. Limite e continuidade. Curvas parametrizadas no Plano. </span> \
06 . &nbsp; Ter  --  08/04  --  <span style="color:standard"> Curvas parametrizadas no Espaço. Hélices. Parametrização de curvas como interseção de duas superfícies. (houve um problema com o último exemplo. Resolução [aqui](exemplo-esfera-cilindro.pdf)) </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  10/04  --  Feriado Municipal </span> \
07 . &nbsp; Seg  --  14/04  --  <span style="color:standard"> Parametrização de curvas como interseção de duas superfícies (continuação). Derivadas </span> \
08 . &nbsp; Ter  --  15/04  --  <span style="color:standard"> Aula de Exercícios.   </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  18/04  --  Sexta-feira da Paixão </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  21/04  --  Tiradentes </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  22/04  --  Não Haverá Aula </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  23/04  --  São Jorge </span> \
09 . &nbsp; Seg  --  28/04  --  <span style="color:standard">Regras de derivação de funções vetoriais. Comprimento de arco. Função comprimento de arco. </span> \
10 . &nbsp; Ter  --  29/04  --  <span style="color:standard"> Parametrização pelo comprimento de arco. Vetor Tangente. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  01/05  --  Dia do Trabalho </span> \
11 . &nbsp; Seg  --  05/05  --  <span style="color:standard"> Definição de Curvatura.  Fórmulas da curvatura. Exercícios. Movimento no espaço: velocidade e aceleração </span> \
12 . &nbsp; Ter  --  06/05  --  <span style="color:standard"> Aula de Exercícios\
13 . &nbsp; Seg  --  12/05  --  <span style="color:standard"> Aula de Exercícios </span> \
<span style="color:red"> 14 . &nbsp; Ter  --  13/05  --  1ª VA -- [gabarito](../provas/2025-1-p1-turmaM2-c3-gabarito.pdf)</span> \
---

**2. Funções de Várias Variáveis**

15 . &nbsp; Seg  --  19/05  --  <span style="color:standard"> Definição de Funções de Várias Variáveis. Gráficos de funções de 2 variáveis. Curvas de Nível. Superfícies de nível.  </span> \
16 . &nbsp; Ter  --  20/05  --  <span style="color:standard"> Não houve aula.  </span> \
17 . &nbsp; Seg  --  26/05  --  <span style="color:standard"> Limites e continuidade. </span> \
18 . &nbsp; Ter  --  27/05  --  <span style="color:standard">Derivadas Parciais. Derivadas de ordem superior. EPDs: Funções Harmônicas, Equação da Onda e equação do calor. </span> \
19 . &nbsp; Seg  --  02/06  --  <span style="color:standard"> Regra da cadeia. Resolução do Para casa 7 item 1.  </span> \
20 . &nbsp; Ter  --  03/06  --  <span style="color:standard">Vetor Gradiente. Derivadas direcionais. Propriedades do vetor Gradiente</span> \
21 . &nbsp; Seg  --  09/06  --  <span style="color:standard"> Valores Máximo e Mínimo. Pontos críticos. Teste da Derivada Segunda </span> \
22 . &nbsp; Ter  --  10/06  --  <span style="color:standard">Teste da Derivada Segunda (continuação) Topologia do $\mathbb{R}^2$. Máximos e Mínimos absolutos. Teorema de Weiestrass. </span> \
23 . &nbsp; Seg  --  16/06  --  <span style="color:standard">Multiplicadores de Lagrange em $\mathbb{R}^2$. Multiplicadores de Lagrange em $\mathbb{R}^3$</span> \
24 . &nbsp; Ter  --  17/06  --  <span style="color:standard">Aproximação linear e plano tangente.</span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  19/06  --  Corpus Christ </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  20/06  --  Ponto Facultativo </span> \
25 . &nbsp; Seg  --  23/06  --  <span style="color:standard"> Aula de Exercícios </span> \
26 . &nbsp; Ter  --  24/06  --  <span style="color:standard"> Atividade Avaliativa (opicional) valendo 30% da nota da 2ª VA -- [gabarito](../provas/2025-1-apva2-turmaM1-c3-gabarito.pdf) </span> \
27 . &nbsp; Seg  --  30/06  --  <span style="color:standard"> Aula de Exercícios </span> \
<span style="color:red"> 28 . &nbsp; Ter  --  01/07  --  2ª VA </span> \
---

**Verificações Finais**

<span style="color:red"> 29 . &nbsp; Seg  --  07/07  --  2ª Chamada </span> \
30 . &nbsp; Ter  --  08/07  --  <span style="color:DarkGray"> Atendimento no gabinete </span> \
<span style="color:red"> 31 . &nbsp; Seg  --  14/07  --  VS </span> \
32 . &nbsp; Ter  --  15/07  --  <span style="color:DarkGray">  --  </span> \
33 . &nbsp; Seg  --  21/07  --  <span style="color:DarkGray">  --  </span> \
34 . &nbsp; Ter  --  22/07  --  <span style="color:DarkGray">  --  </span> \
:end: &nbsp; Sáb  --  26/07  --  Fim do Período. :raised_hands:
---


# Resultados

```{python}
#| echo: false
#| output: asis

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt

insc=32

print('## 1ª Verificação de Aprendizagem {-}')

p1 = np.array([
3.1,
5.2,
2.1,
7,
5.9,
6.8,
8.,
7.8,
6.4,
6.3,
5.4,
2.7,
5.7,
1.6,
10.,
6.6,
5.8,
6.8,
7.7,
2.9,
5.9,
4.,
2.1,
8.,
8.9
])
N=len(p1)

ab=insc-N
est=np.array([ab,N])
perc = np.round(est/est.sum(axis=0)*100,2)

print('Compareceram à 1ª verificação ','**'+str(N)+'**',' alunos, de um total de',' **'+str(insc)+'**',' inscritos, isto é, ',round(N/insc*100,2),'%.')
print( )

# Plot the histogram.
plt.hist(p1, bins=10, density=False, alpha=0.6, color='b',edgecolor='black')

# Adicionar título e legendas
plt.title("Histograma das Notas da P1")
plt.xlabel('Notas')
plt.ylabel('Nº de alunos')

plt.show()

bins = [0, 4, 6, 10]

res1, _ = np.histogram(p1, bins=bins)

print(' ')
print('|Classificação | Notas | Porcentagem|')
print('|---|---|---|')
print('| Notas acima de 6    |',res1[2],' |',np.round(res1[2]/N*100,2),'%  |')
print('| Notas entre 4 e 6   |',res1[1],' |',np.round(res1[1]/N*100,2),'%  |')
print('| Notas abaixo de 4   |',res1[0],' |',np.round(res1[0]/N*100,2),'%  |')
print('| Total      |',N,' |',100,'%  |\n')
print(': Resumo {.striped .hover #tbl-p1}')
```


# Cronograma Proposto Incialmente

Este foi o programa proposto no início do perído, que será mantido aqui para fins de comparação com o cronograma que realmente foi efetivado acima.


**1. Funções vetoriais e Superfícies**

01 . &nbsp; Seg  --  24/03  --  <span style="color:standard"> Apresentação do curso. revisão de equação paramétrica da reta e equação cartesiana do plano em $\mathbb{R}^3.$ </span> \
02 . &nbsp; Ter  --  25/03  --  <span style="color:standard"> Coordenadas Polares. Superfícies  Cilíndricas. Superfícies de revolução :fist: </span> \
03 . &nbsp; Seg  --  31/03  --  <span style="color:standard"> Superfícies Quádricas. </span> \
04 . &nbsp; Ter  --  01/04  --  <span style="color:standard"> Aula de Exercícios 1. </span> \
05 . &nbsp; Seg  --  07/04  --  <span style="color:standard"> Funções Vetoriais. Limite e continuidade. Curvas parametrizadas no Plano. </span> \
06 . &nbsp; Ter  --  08/04  --  <span style="color:standard"> Coordenadas polares. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  10/04  --  Feriado Municipal </span> \
07 . &nbsp; Seg  --  14/04  --  <span style="color:standard"> Curvas parametrizadas no Espaço. Hélices. Parametrização de curvas como interseção de duas superfícies. </span> \
08 . &nbsp; Ter  --  15/04  --  <span style="color:standard"> Derivadas e regras de derivação de funções vetoriais. Comprimento de arco. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  18/04  --  Sexta-feira da Paixão </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  21/04  --  Tiradentes </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  22/04  --  Não Haverá Aula </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  23/04  --  São Jorge </span> \
09 . &nbsp; Seg  --  28/04  --  <span style="color:standard"> Aula de Exercícios 2  </span> \
10 . &nbsp; Ter  --  29/04  --  <span style="color:standard"> Parametrização pelo comprimento de arco. Vetor Tangente e Curvatura. Vetores Normal e Binormal. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  01/05  --  Dia do Trabalho </span> \
11 . &nbsp; Seg  --  05/05  --  <span style="color:standard"> Movimento, velocidade e aceleração.  Componentes Normal e Tangencial da Aceleração. Fórmula da curvatura. </span> \
12 . &nbsp; Ter  --  06/05  --  <span style="color:standard"> Aula de Exercícios 3 </span> \
<span style="color:red"> 13 . &nbsp; Seg  --  12/05  --  1ª VA </span> \
---

**2. Funções de Várias Variáveis**

14 . &nbsp; Ter  --  13/05  --  <span style="color:standard"> Definição de Funções de Várias Variáveis. Gráficos de funções de 2 variáveis. Curvas de Nível. Superfícies de nível.  </span> \
15 . &nbsp; Seg  --  19/05  --  <span style="color:standard"> Limites e continuidade. </span> \
16 . &nbsp; Ter  --  20/05  --  <span style="color:standard"> Derivadas Parciais. Derivadas de ordem superior.  EPDs: Funções Harmônicas e Equação da Onda. </span> \
17 . &nbsp; Seg  --  26/05  --  <span style="color:standard"> Plano tangente. Aproximação linear.  </span> \
18 . &nbsp; Ter  --  27/05  --  <span style="color:standard"> Diferenciabilidade em $\mathbb{R}^2$. Função de classe $C^1$ e diferenciais em $\mathbb{R}^2$. </span> \
19 . &nbsp; Seg  --  02/06  --  <span style="color:standard"> Diferenciabilidade e diferenciais em $\mathbb{R}^3$. Regra da cadeia. </span> \
20 . &nbsp; Ter  --  03/06  --  <span style="color:standard"> Aula de Exercícios 4 </span> \
21 . &nbsp; Seg  --  09/06  --  <span style="color:standard"> Vetor Gradiente. Derivadas direcionais. Propriedades do vetor Gradiente </span> \
22 . &nbsp; Ter  --  10/06  --  <span style="color:standard"> Derivação Implícita e Teorema da Função Implícita em $\mathbb{R}^2$. </span> \
23 . &nbsp; Seg  --  16/06  --  <span style="color:standard"> Derivação Implícita e Teorema da Função Implícita em $\mathbb{R}^3$. Valores Máximo e Mínimo. Pontos críticos. Teste da Derivada Segunda </span> \
24 . &nbsp; Ter  --  17/06  --  <span style="color:standard"> Topologia do $\mathbb{R}^2$. Máximos e Mínimos absolutos. Teorema de Weiestrass. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  19/06  --  Corpus Christ </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  20/06  --  Ponto Facultativo </span> \
25 . &nbsp; Seg  --  23/06  --  <span style="color:standard"> Multiplicadores de Lagrange em $\mathbb{R}^2$. Multiplicadores de Lagrange em $\mathbb{R}^3$ </span> \
26 . &nbsp; Ter  --  24/06  --  <span style="color:standard"> Multiplicadores de Lagrange com duas restrições </span> \
27 . &nbsp; Seg  --  30/06  --  <span style="color:standard"> Aula de Exercícios 5 </span> \
<span style="color:red"> 28 . &nbsp; Ter  --  01/07  --  2ª VA </span> \
---

**VAs Finais**

<span style="color:red"> 29 . &nbsp; Seg  --  07/07  --  2ª Chamada </span> \
30 . &nbsp; Ter  --  08/07  --  <span style="color:standard"> Atendimento no gabinete </span> \
<span style="color:red"> 31 . &nbsp; Seg  --  14/07  --  VS </span> \
32 . &nbsp; Ter  --  15/07  --  <span style="color:standard">  --  </span> \
33 . &nbsp; Seg  --  21/07  --  <span style="color:standard">  --  </span> \
34 . &nbsp; Ter  --  22/07  --  <span style="color:standard">  --  </span> \
:end: &nbsp; Sáb  --  26/07  --  Fim do Período. :raised_hands:
---