---
title: GAAL RCN00075 -- 2024-1
number-sections: true
bibliography: biblio.bib
csl:  aims-mathematics.csl
nocite: |
  @*

format:
  html:
    toc: true
from: markdown+emoji
---
# Informações Básicas

- **Início e Fim do Período:** 18/03/2024 a 17/07/2024 

-  **Horário e sala:** 2ª (16h às 18h) e 3ª (14h às 16h) -- **sala 06 -- IHS (prédio alugado)**\
confira no [Quadro de Alocação de salas do IHS](http://200.159.243.2:10032/home/index_simples)

-  **Atendimento:** sala 104 -- IHS (prédio alugado) -- Enviar [email](mailto:reginaldodr@id.uff.br) agendando horário.


- **Material a ser utilizado**
    - [Slides e outros](gaal.qmd)

    - [Anotações das aulas](https://mega.nz/folder/PRF2mAbR#BzPLXunAv1ekFN1d1n6_dw)


-  **Ementa:** Busque por RCN00075 em [quadro de horários](https://app.uff.br/graduacao/quadrodehorarios/):\
MATRIZES E SISTEMAS LINEARES. DETERMINANTES. VETORES NO PLANO E NO ESPAÇO. RETAS E PLANOS. ESPAÇO $\mathbb{R}^n$. AUTOVALORES E AUTOVETORES DE UMA MATRIZ. DIAGONALIZAÇÃO DE MATRIZES. RECONHECIMENTO DE CÔNICAS.

- **Monitoria:** Aguardando o processo seletivo.

# Apresentação do Curso

Este curso é constituído de dois módulos:

1. Matrizes, Sistemas lineares, Determinates e Geometria Analítica;
2. Álgebra Linear no $\mathbb{R}^n$.

Usaremos o **Classroom** como Ambiente Virtual de Aprendizagem (AVA), onde serão postadas as notas e realizadas as discussões e comunicações.

Usaremos como livro texto as referências [@poole] e [@santosufmg]. **A primeira está disponível para empréstimo na Biblioteca do campus** -- [BRO](https://bibliotecas.uff.br/bro/). A segudna pode ser baixada [aqui](gaalt0.pdf). <span style="color:red">  É altamente recomendado que vocês consultem este material, de preferência, o livro físico.</span>

As demais referência contidas na @sec-ref serão usadas como material auxiliar ao longo do curso.\


# Avaliação

A avaliação será feita mediante:

1. Exercícios propostos, chamados de **Para Casa** :house: [veja aqui](paracasa.pdf) , que deverão ser entregues ao final de cada módulo.
2. Um **trabalho escrito** sobre cônicas: elípse, hipérbole e parábola.
3. **Prova Final** contemplando toda a matéria do curso. 

A nota final será a média ponderada entre os **Para Casa**, o **Trabalho escrito** e a **Prova Final**, isto é, 
$$N=0.2\times PC+0.1\times T+0.7\times PF,$$
onde $PC$ é a nota dos Para Casa, $T$ é a nota do Trabalho Escrito e $PF$ a nota da Prova Final. Veja no cronograma, @sec-crono abaixo, as datas destas avaliações. 

## Sobre o Trabalho Escrito

- Tema: Cônicas: Elipse, hipérbole e parábola
    - **Referências:** Seção 10.5 da referência [@stewart2] 
    - **Videoaulas**: 
      - [Elipse I](https://youtu.be/vp8WPjaLN-4?si=-wVB9AQly7EqlacU) 
      - [Elipse II](https://youtu.be/ELZ5B_RPJk4?si=NVoPVuG1UOy8u_6_)
      - [Hipérbole I](https://youtu.be/64mXj1iI7xI?si=E2uZ0HVwDD_mUodT)
      - [Hipérbole II](https://youtu.be/XhjgiH3Q6O0?si=rj6tCPy6eZC7ch9N)
      - [Parábola I](https://youtu.be/FEtPwrJleWM?si=2N_4uvQPQ6WVkpy9)
      - [Parábola II](https://youtu.be/i_GFd-bayjM?si=sSIeghOXFZazJdTA)
- Deverá ser feito em grupos de 4 a 5 integrantes.
- Deverá ser manuscrito.
- Data de entrega ver @sec-crono. 


## Sobre a Prova

- Será **escritas e com consulta** a qualquer material impresso ou manuscrito (livros, notas de aula, caderno, apostilas e etc.).
- <span style="color:red"> Não será permitido o uso de dispositivos eletrônicos com acesso à internet (tablets, celulares e etc).</span> 
- Será permitido o uso de calculadora científica.


## Segunda Chamada

O Art. 98 do  [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) garante ao aluno  o direito a uma avaliação de **Segunda Chamada (VR)**, <span style="color:red">sem a necessidade de justificativa!</span> Portanto, aquele aluno que **não puder ou não quiser** fazer uma das provas, poderá faltar que seu direito à Segunda Chamada será garantido.

Como só haverá uma prova escrita, a Segunda Chamada será referente apenas a esta avaliação.


::: {.callout-warning}
## Importante

Como **não há a necessidade de justificar a falta nas avaliações** para ter o direito à Segunda Chamada garantido, alguns alunos usam este direito para fazer a Segunda Chamada quando não se sentem suficientemente preparados para alguma das avaliações. 

Por conta disso, o aluno que estiver em dúvida entre fazer a prova ou a Segunda chamada, poderá comparecer no dia da prova e tentar fazê-la. Caso não se sinta preparado, poderá desistir e ainda terá o direito a fazer a Segunda Chamada. Aqueles que permanecerem e entregarem definitivamente a prova não terão o direito à Segunda Chamada.
:::

## Verificação Suplementar

Em concordância com o [Regulamento dos Cursos de graduação](http://www.uff.br/sites/default/files/001-2015_regulamento_do_curso_de_graduacao_0.pdf#page=55) em seu Art. 99, a **Verificação Suplementar (VS)** é vetada aos discentes já aprovados e é **obrigatória** para aqueles que tenham obtido média parcial entre 4,0 e 5,9, sendo esses dois limites incluídos.


# Listas de Exercícios

Abaixo seguem os execícios das referências @poole e @santosufmg que devem ser feitos a fim de se preparar para a avaliação escrita. Os exercícios marcado com o símbolo SAC no livro, devem ser feitos usando uma ferramenta computacional, como por exemplo o python.

@poole **§ 1.2:** 5, 11, 12, 14, 17 .\
@poole **§ 3.2:** 1, 11, 13, 17, 35 .\
@poole **§ 1.3:** 1, 3, 5, 7, 9, 17, 19, 21, 23, 27, 29, 39, 46, 47, 51.\
@poole **§ 1.4:** 3, 5, 7,  11, 15, 17, 21, 23 .\
@poole **§ 2.2:** 1, 3, 5, 15, 17, 27, 29, 31 .\
@poole **§ 2.3:** 9, 11,  13, 23, 25, 27, 29, 31, 39, 41, 43, 47  .\
:construction: Em construção... 

# Referências {#sec-ref}


::: {#refs}
:::

# Cronograma {#sec-crono}

A seguir temos a proposta de cronograma para este curso. Esta proposta pode sofrer pequenas alterações ao longo do curso que, caso ocorram, serão comunicadas aos alunos. **Cabe ressaltar que o semestre se encerra no dia 17/07, neste caso, é aconselhado que fiquem disponíveis até esta data.**

## Cronograma Efetivado

**1. Matrizes, Sistemas lineares, Determinates e Geometria Analítica;**

01 . &nbsp; Seg  --  18/03  --  <span style="color:Black"> Apresentação. Coordenadas cartesianas no plano. Espaço Vetorial $\mathbb{R}^2$.  Representação Geométrica. Norma. Regra do paralelogramo. </span> \
02 . &nbsp; Ter  --  19/03  --  <span style="color:Black"> O espaço vetorial $\mathbb{R}^3$ e representação geométrica. O espaço vetorial $\mathbb{R}^n$. Norma e vetor unitário. Combinação Linear. </span> \
03 . &nbsp; Seg  --  25/03  --  <span style="color:Black"> Matrizes: definição, operações e propriedades </span> \
04 . &nbsp; Ter  --  26/03  --  <span style="color:Black"> Matrizes identidade e transposta. Operações usando o sympy. Produto escalar no $\mathbb{R}^n$. Ângulo entre vetores. Produto escalar usando o sympy.  </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  29/03  --  Sexta-feira da Paixão </span> \
05 . &nbsp; Seg  --  01/04  --  <span style="color:Black"> Demonstração fórmula do ângulo. Equação paramétrica da reta. Equações Cartesianas da Reta em $\mathbb{R}^2$: parte 1  </span> \
06 . &nbsp; Ter  --  02/04  --  <span style="color:LightGray"> Equações Cartesianas da Reta em $\mathbb{R}^2$: parte 2.  Equação cartesina do Plano em $\mathbb{R}^3$.   </span> \
07 . &nbsp; Seg  --  08/04  --  <span style="color:LightGray">  Sistemas de Equações Lineares. Operações Elementares. Escalonamento </span> \
08 . &nbsp; Ter  --  09/04  --  <span style="color:LightGray"> Posto de uma matriz. Variáveis livres. Usando sympy para resolver sistemas lineares. Método de Gauss-Jordan. Sistemas lineares Homogêneos </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  10/04  --  Feriado Municipal </span> \
09 . &nbsp; Seg  --  15/04  --  <span style="color:LightGray"> Matriz Inversa e Método de Inversão </span> \
10 . &nbsp; Ter  --  16/04  --  <span style="color:LightGray"> Determinantes. </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Dom  --  21/04  --  Tiradentes </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  22/04  --  Não Haverá Aula </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  23/04  --  São Jorge </span> \
11 . &nbsp; Seg  --  29/04  --  <span style="color:LightGray"> Produto Vetorial e Produto Misto </span> \
12 . &nbsp; Ter  --  30/04  --  <span style="color:LightGray"> Distâncias: entre Ponto e Plano, Ponto a Reta </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  01/05  --  Dia do Trabalho </span> \
13 . &nbsp; Seg  --  06/05  --  <span style="color:LightGray"> Distâncias: Entre Retas, entre reta e Plano </span> \
<span style="color:red"> :writing_hand: &nbsp; Entrega dos Para Casa :house: na próxima aula </span> \
<span style="color:red"> :memo: &nbsp; Entrega do Trabalho para a próxima aula </span> \
---

**2. Álgebra Linear no $\mathbb{R}^n$**

14 . &nbsp; Ter  --  07/05  --  <span style="color:LightGray"> Dependência e Independência Linear </span> \
15 . &nbsp; Seg  --  13/05  --  <span style="color:LightGray"> Posição Relativa de retas e planos </span> \
16 . &nbsp; Ter  --  14/05  --  <span style="color:LightGray"> Subespaço. Base e Dimensão </span> \
17 . &nbsp; Seg  --  20/05  --  <span style="color:LightGray"> Aula de Exercícios </span> \
18 . &nbsp; Ter  --  21/05  --  <span style="color:LightGray"> Projeção Ortogonal. Bases Ortogonais e Ortonormais. </span> \
19 . &nbsp; Seg  --  27/05  --  <span style="color:LightGray"> Mudança de Coordenadas. Rotação e Translação </span> \
20 . &nbsp; Ter  --  28/05  --  <span style="color:LightGray"> Autovetores e Autovalores </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  30/05  --  Corpus Christ </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  31/05  --  Ponto Facultativo </span> \
21 . &nbsp; Seg  --  03/06  --  <span style="color:LightGray"> Diagonalização de Matrizes </span> \
22 . &nbsp; Ter  --  04/06  --  <span style="color:LightGray"> Diagonalização de Matrizes Simétricas </span> \
23 . &nbsp; Seg  --  10/06  --  <span style="color:LightGray"> Reconhecimento de Cônicas </span> \
24 . &nbsp; Ter  --  11/06  --  <span style="color:LightGray"> Aula de Exercícios </span> \
25 . &nbsp; Seg  --  17/06  --  <span style="color:LightGray"> Aula de Dúvidas </span> \
<span style="color:red"> :writing_hand: &nbsp; Entrega dos Para Casa :house: na próxima aula </span> \
---

**Provas Finais**

<span style="color:red"> 26 . &nbsp; Ter  --  18/06  --  Prova da Matéria Toda </span> \
27 . &nbsp; Seg  --  24/06  --  <span style="color:LightGray"> Vista da Prova. </span> \
<span style="color:red"> 28 . &nbsp; Ter  --  25/06  --  2ª Chamada </span> \
29 . &nbsp; Seg  --  01/07  --  <span style="color:LightGray"> Semana dedicada à preparação para a VS </span> \
30 . &nbsp; Ter  --  02/07  --  <span style="color:LightGray"> Semana dedicada à preparação para a VS </span> \
<span style="color:red"> 31 . &nbsp; Seg  --  08/07  --  VS </span> \
32 . &nbsp; Ter  --  09/07  --  <span style="color:LightGray">  --  </span> \
33 . &nbsp; Seg  --  15/07  --  <span style="color:LightGray">  --  </span> \
34 . &nbsp; Ter  --  16/07  --  <span style="color:LightGray">  --  </span> \
:end: &nbsp; Qua  --  17/07  --  Fim do Período. :raised_hands:
---

## Crongrama Porposto Inicialmente

Este foi o programa proposto no início do perído, que será mantido aqui para fins de comparação com o cronograma que realmente foi efetivado acima.

**1. Matrizes, Sistemas lineares, Determinates e Geometria Analítica;**

01 . &nbsp; Seg  --  18/03  --  Apresentação. Coordenadas cartesianas no plano. Espaço Vetorial $\mathbb{R}^2$.  Representação Geométrica. Norma. Regra do paralelogramo. \
02 . &nbsp; Ter  --  19/03  --  O espaço vetorial $\mathbb{R}^3$ e representação geométrica. O espaço vetorial $\mathbb{R}^n$. Norma e vetor unitário. Combinação Linear. \
03 . &nbsp; Seg  --  25/03  --  Matrizes: definição, operações e propriedades \
04 . &nbsp; Ter  --  26/03  --  Matrizes identidade e transposta. Operações usando o sympy. \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  29/03  --  Sexta-feira da Paixão </span> \
05 . &nbsp; Seg  --  01/04  --  Produto escalar no $\mathbb{R}^n$. Ângulo entre vetores. Produto escalar usando o sympy. \
06 . &nbsp; Ter  --  02/04  --  Equação paramétrica da reta. Equações Cartesianas da Reta em $\mathbb{R}^2$. \
07 . &nbsp; Seg  --  08/04  --  Equação cartesina do Plano em $\mathbb{R}^3$. Sistemas de Equações Lineares. Operações Elementares. Escalonamento \
08 . &nbsp; Ter  --  09/04  --  Posto de uma matriz. Variáveis livres. Usando sympy para resolver sistemas lineares. Método de Gauss-Jordan. Sistemas lineares Homogêneos \
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  10/04  --  Feriado Municipal </span> \
09 . &nbsp; Seg  --  15/04  --  Matriz Inversa e Método de Inversão \
10 . &nbsp; Ter  --  16/04  --  Determinantes. \
:beach_umbrella: <span style="color:orange"> &nbsp; Dom  --  21/04  --  Tiradentes </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Seg  --  22/04  --  Não Haverá Aula </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Ter  --  23/04  --  São Jorge </span> \
11 . &nbsp; Seg  --  29/04  --  Produto Vetorial e Produto Misto \
12 . &nbsp; Ter  --  30/04  --  Distâncias: entre Ponto e Plano, Ponto a Reta \
:beach_umbrella: <span style="color:orange"> &nbsp; Qua  --  01/05  --  Dia do Trabalho </span> \
13 . &nbsp; Seg  --  06/05  --  Distâncias: Entre Retas, entre reta e Plano \
<span style="color:red"> :writing_hand: &nbsp; Entrega dos Para Casa :house: na próxima aula </span> \
<span style="color:red"> :memo: &nbsp; Entrega do Trabalho </span> \
---

**2. Álgebra Linear no $\mathbb{R}^n$**

14 . &nbsp; Ter  --  07/05  --  Dependência e Independência Linear \
15 . &nbsp; Seg  --  13/05  --  Posição Relativa de retas e planos \
16 . &nbsp; Ter  --  14/05  --  Subespaço. Base e Dimensão \
17 . &nbsp; Seg  --  20/05  --  Aula de Exercícios \
18 . &nbsp; Ter  --  21/05  --  Projeção Ortogonal. Bases Ortogonais e Ortonormais. \
19 . &nbsp; Seg  --  27/05  --  Mudança de Coordenadas. Rotação e Translação \
20 . &nbsp; Ter  --  28/05  --  Autovetores e Autovalores \
:beach_umbrella: <span style="color:orange"> &nbsp; Qui  --  30/05  --  Corpus Christ </span> \
:beach_umbrella: <span style="color:orange"> &nbsp; Sex  --  31/05  --  Ponto Facultativo </span> \
21 . &nbsp; Seg  --  03/06  --  Diagonalização de Matrizes \
22 . &nbsp; Ter  --  04/06  --  Diagonalização de Matrizes Simétricas \
23 . &nbsp; Seg  --  10/06  --  Reconhecimento de Cônicas \
24 . &nbsp; Ter  --  11/06  --  Aula de Exercícios \
25 . &nbsp; Seg  --  17/06  --  Aula de Dúvidas \
<span style="color:red"> :writing_hand: &nbsp; Entrega dos Para Casa :house: na próxima aula </span> \
---

**Provas Finais**

<span style="color:red"> 26 . &nbsp; Ter  --  18/06  --  Prova da Matéria Toda </span> \
27 . &nbsp; Seg  --  24/06  --  Vista da Prova. \
<span style="color:red"> 28 . &nbsp; Ter  --  25/06  --  2ª Chamada </span> \
29 . &nbsp; Seg  --  01/07  --  Semana dedicada à preparação para a VS \
30 . &nbsp; Ter  --  02/07  --  Semana dedicada à preparação para a VS \
<span style="color:red"> 31 . &nbsp; Seg  --  08/07  --  VS </span> \
32 . &nbsp; Ter  --  09/07  --   --  \
33 . &nbsp; Seg  --  15/07  --   --  \
34 . &nbsp; Ter  --  16/07  --   --  \
:end: &nbsp; Qua  --  17/07  --  Fim do Período. :raised_hands:
---
